/-
Copyright (c) 2025 Alex Bishop. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Alex Bishop
-/
module

public import Mathlib.Logic.Equiv.Defs
public import Mathlib.Data.Fintype.Defs
public import Mathlib.Data.List.Defs
public import Mathlib.Logic.Relation
public import Mathlib.Computability.Language

import Mathlib.Data.List.Basic
import Mathlib.Logic.Equiv.Basic

/-!
# EDT0L Languages

This file contains a definition of the class of EDT0L languages.  Such classes of languages are
described by EDT0L grammars of which we now give a formal mathematical description of the family
of such grammars and their operation as follows.

An EDT0L grammar consists of the following data
* a finite alphabet of *terminal letters* `α`;
* a finite alphabet of *nonterminal letters/variables* `V`;
* an *initial* nonterminal `initial : V`; and
* a finite number of maps of the form `N → List (Symbol α V)` which we call *tables*.
Note here that `Symbol α V` should be understood as the disjoint union of the types `α` and `V`.

Given some table `t : V → List (Symbol α V)`, we can then extend `t` to act on lists of symbols by
leaving every terminal alone, and rewriting the nonterminals.  That is, we define the map
`List.flatMap (fun | .terminal a => [.terminal a] | .nonterminal v => t v)`.  We then say that some
word `w : List α` is *generated* by the grammar if we can obtain `w.map .terminal` from the list
`[.nonterminal intial]` by a finite number of applications of tables.  The set of all such words is
then called an *EDT0L language*.

## Main definitions

* `EDT0LGrammar α V T`: an EDT0L grammar with terminals `α`, nonterminals `V`, and tables
  parameterised by the type `T`;
* `EDT0LGrammar.language`: the set of all words generated by a given `EDT0LGrammar`;
* `Language.IsEDT0L`: a predicate indicating that the given language has a corresponding EDT0L
  grammar with finitely many terminals, nonterminals, and tables; and
* `EDT0LGrammar.equiv`: an equivalence relation on EDT0L grammars.

We note here that our definition `EDT0LGrammar` does not require the types `α`, `V` or `T` to be
finite.  However this requirement does appear in the definition `Language.IsEDT0L`.  Our reason for
this design pattern is to make it easier to work with the definitions.  In particular, this way one
could delay the proof of finiteness of these assocated types.

## Main theorem

* `EDT0LGrammar.equiv_language_eq_language`: shows that under some hypothesis, the equivalence
  relation produced by `EDT0LGrammar.equiv` preserves the language; and
* `EDT0LGrammar.language_isEDT0L`: Given an EDT0L grammar `E : EDT0LGrammar α V T`, and the
  hypotheses `Finite V` and `Finite T`, this result shows `E.language.IsEDT0L`.  (This is needed as
  a lemma as the definition `Language.IsEDT0L` requires both `V` and `T` to be types of the form
  `Fin m` and `Fin k` for some `m k : ℕ`.)
-/

@[expose] public section

/--
An EDT0L grammar where `α` is the terminal alpabet, `V` is the nonterminal alphabet, and `T` is a
type used to index the colection of tables.  Note that we do not require `α`, `V`, or `T` to be
finite here: you only need to prove that `V` and `T` are finite if you are making use of a lemma
or definition which explicitly requires it.
-/
@[ext]
structure EDT0LGrammar (α V T : Type*) where
  /-- The initial nonterminal of the grammar. -/
  initial : V
  /-- The finite set of tables, indexed by `T`. -/
  table : T → V → List (Symbol α V)

/- the following namespace give a complete description of EDT0L language -/
namespace EDT0LGrammar
variable {α V T : Type*} (E : EDT0LGrammar α V T)
include E

/-- The initial word of the grammar. -/
abbrev initialWord : List (Symbol α V) := [.nonterminal E.initial]

/-- Extends a table so that acts on `Symbol α V`. -/
def rewriteSymbol (t : T) : Symbol α V → List (Symbol α V)
  | .terminal a => [ .terminal a ]
  | .nonterminal v => E.table t v

/-- Extends a table so that it acts on words of the form `List (Symbol α V)`. -/
def rewriteWord (t : T) : List (Symbol α V) → List (Symbol α V) := List.flatMap (E.rewriteSymbol t)

/-- A predicate indicating that there exists some table `t : T` such that
`E.rewriteWord t source = target`.  That is, this predicate indicates that the grammar can rewrite
the word `source` to the word `target`. -/
def Rewrites (source target : List (Symbol α V)) : Prop :=
  ∃ t : T, E.rewriteWord t source = target

/-- The reflexive transitive closure of `EDT0LGrammar.Rewrites`. -/
def Derives : List (Symbol α V) → List (Symbol α V) → Prop := Relation.ReflTransGen E.Rewrites

/-- A predicated indicating that a word can be derived from the initial word. -/
def Generates (w : List (Symbol α V)) : Prop := E.Derives E.initialWord w

/-- The language of all words, in terminals only, which can be generated by the EDT0L grammar. -/
def language : Language α := { w : List α | E.Generates (w.map Symbol.terminal) }

end EDT0LGrammar

/-- The language is EDT0L.

Notice that this definition requries that the language is generated by an EDT0L language where the
set of nonterminals and terminals are of the form `Fin n` and `Fin m`, respectively, for some
`n m : ℕ`.  Our main goal in this file is to show that we can assume without loss of generality that
any given EDT0L grammar is of this form.  We prove this fact in the theorem 
`edt0l_grammars_generate_edt0l_languages`, at the end of this module. -/
def Language.IsEDT0L {α : Type*} (L : Language α) : Prop :=
  ∃ n m : ℕ, ∃ E : EDT0LGrammar α (Fin n) (Fin m), E.language = L

namespace EDT0LGrammar
variable {α V T : Type*}

section Basics
variable (E : EDT0LGrammar α V T)

/-- A word belongs to the language of an EDT0L grammar if and only if it is generated by the
grammar. -/
@[simp]
lemma language_mem_iff {w} : w ∈ E.language ↔ E.Generates (w.map Symbol.terminal) := Iff.of_eq rfl

end Basics

/-! We now move onto some basic lemmas involving our previous definitions. --/

section RewriteSymbol
variable (E : EDT0LGrammar α V T) (t : T)

@[simp]
lemma rewriteSymbol_terminal {a : α} : E.rewriteSymbol t (.terminal a) = [.terminal a] := rfl

@[simp]
lemma rewriteSymbol_nonterminal {v : V} : E.rewriteSymbol t (.nonterminal v) = E.table t v := rfl

end RewriteSymbol

section RewriteWord
variable (E : EDT0LGrammar α V T) (t : T)

@[simp]
lemma rewriteWord_nil : E.rewriteWord t [] = [] := rfl

@[simp]
lemma rewriteWord_cons {x : Symbol α V} {xs : List (Symbol α V)} :
    E.rewriteWord t (x::xs) = (E.rewriteSymbol t x) ++ (E.rewriteWord t xs) := rfl

@[simp]
lemma rewriteWord_append {w₁ w₂ : List (Symbol α V)} :
    E.rewriteWord t (w₁ ++ w₂) = (E.rewriteWord t w₁) ++ (E.rewriteWord t w₂) := List.flatMap_append

@[simp]
lemma rewriteWord_single {x : Symbol α V} :
    E.rewriteWord t [x] = E.rewriteSymbol t x := List.flatMap_singleton _ _

@[simp]
lemma rewriteWord_terminals {w : List α} :
    E.rewriteWord t (w.map .terminal) = (w.map .terminal) := by
  induction w with
  | nil => exact List.toList_toArray
  | cons a as ih =>
    rw [List.map_cons, rewriteWord_cons, rewriteSymbol_terminal, ih, List.cons_append,
      List.nil_append]

end RewriteWord

-- rewrites definition

section Rewrites
variable (E : EDT0LGrammar α V T) (t : T)

lemma rewrites_nil {w : List (Symbol α V)} (h : E.Rewrites [] w) : w = [] := by
  obtain ⟨t, rfl⟩ := h
  exact rewriteWord_nil _ _

lemma rewrites_terminals {w : List α} {w' : List (Symbol α V)}
  (h : E.Rewrites (w.map .terminal) w') :
    w' = (w.map .terminal) := by
  replace ⟨t, h⟩ := h
  rw [rewriteWord_terminals] at h
  rw [← h]

end Rewrites

-- The following namespace contains proofs that Derives is reflexive and transitive
-- and the corresponding type class instanciations. These type classes are needed if
-- you want to use the `calc` tactic.

section Derives
section lemmas_for_derives
variable {x y z : List (Symbol α V)}
variable {E : EDT0LGrammar α V T}

lemma derives_trans (h₁ : E.Derives x y) (h₂ : E.Derives y z) : E.Derives x z :=
  Relation.ReflTransGen.trans h₁ h₂

lemma derives_single (h : E.Rewrites x y) : E.Derives x y :=
  Relation.ReflTransGen.single h

lemma derives_head (h₁ : E.Rewrites x y) (h₂ : E.Derives y z) : E.Derives x z :=
  Relation.ReflTransGen.head h₁ h₂

lemma derives_tail (h₁ : E.Derives x y) (h₂ : E.Rewrites y z) : E.Derives x z :=
  Relation.ReflTransGen.tail h₁ h₂

lemma derives_refl : E.Derives x x :=
  Relation.ReflTransGen.refl

end lemmas_for_derives

lemma derives_tail' {x y : List (Symbol α V)} {E : EDT0LGrammar α V T} (h₁ : E.Derives x y) (t) :
    E.Derives x (E.rewriteWord t y) :=
  Relation.ReflTransGen.tail h₁ ⟨t, rfl⟩

section lemmas_for_generates
variable {x y : List (Symbol α V)}
variable {E : EDT0LGrammar α V T}

lemma generates_derives_tail (h₁ : E.Generates x) (h₂ : E.Derives x y) : E.Generates y :=
  Relation.ReflTransGen.trans h₁ h₂

lemma generates_rewrites_tail (h₁ : E.Generates x) (h₂ : E.Rewrites x y) : E.Generates y :=
  Relation.ReflTransGen.tail h₁ h₂

lemma generates_rewriteWord_tail (h₁ : E.Generates x) (t : T) : E.Generates (E.rewriteWord t x) :=
  Relation.ReflTransGen.tail h₁ ⟨t, rfl⟩

end lemmas_for_generates

section class_instances_for_derives
variable (E : EDT0LGrammar α V T)

instance : Trans E.Derives E.Derives E.Derives where
  trans h₁ h₂ := derives_trans h₁ h₂

instance : Trans E.Derives E.Rewrites E.Derives where
  trans h₁ h₂ := derives_tail h₁ h₂

instance : Trans E.Rewrites E.Derives E.Derives where
  trans h₁ h₂ := derives_head h₁ h₂

instance : Trans E.Rewrites E.Rewrites E.Derives where
  trans h₁ h₂ := derives_tail (derives_single h₁) h₂

instance : IsTrans (List (Symbol α V)) E.Derives where
  trans _ := fun _ _ hxy hyz ↦ derives_trans hxy hyz

instance : IsPreorder (List (Symbol α V)) E.Derives where
  trans _ := fun _ _ hxy hyz ↦ derives_trans hxy hyz
  refl _ := derives_refl

end class_instances_for_derives
end Derives

-- some additional lemmas about derives

section Derives
variable (E : EDT0LGrammar α V T)

lemma derives_nil {w : List (Symbol α V)}
  (h : E.Derives [] w) :
    w = [] := by
  induction h with
  | refl => rfl
  | tail h_a hab ha =>
    rename_i a b
    subst ha
    exact rewrites_nil E hab

lemma derives_terminals {w : List α} {w' : List (Symbol α V)}
  (h : E.Rewrites (w.map .terminal) w') :
    w' = (w.map .terminal) := by
  replace ⟨τ,h⟩ := h
  rw [rewriteWord_terminals] at h
  exact Eq.symm h

end Derives

-- generates

section Generates
variable (E : EDT0LGrammar α V T) in
lemma generates_initial : E.Generates E.initialWord := Relation.ReflTransGen.refl
end Generates

/--
Recursor for `EDT0LGrammar.Derives`.  This theorem is marked as the default one to be used by the
`induction` tactic.  This theorem is given so as to avoids unfolding the `Derives` definition when
performing inductions.
-/
@[induction_eliminator]
theorem Derives.recOn {α V T} {E : EDT0LGrammar α V T} {w : List (Symbol α V)}
  {w' : List (Symbol α V)}
  (t : E.Derives w w')
  {motive : (x : List (Symbol α V)) → E.Derives w x → Prop}
  (refl : motive w derives_refl)
  (tail : ∀ {u x} (hwu : E.Derives w u) (hux : E.Rewrites u x),
            motive u hwu → motive x (derives_tail hwu hux)) : motive w' t := by
  induction t with
  | refl => exact refl
  | tail x y h => exact tail x y h

/--
Recursor for `EDT0LGrammar.Generates`.  This theorem is marked as the default one to be used by the
`induction` tactic.  This theorem is given so as to avoids unfolding the `Generates` definition when
performing inductions.
-/
@[induction_eliminator]
theorem Generates.recOn {α V T} {E : EDT0LGrammar α V T}
  {w' : List (Symbol α V)}
  (t : E.Generates w')
  {motive : (w : List (Symbol α V)) → E.Generates w → Prop}
  (refl : motive E.initialWord E.generates_initial)
  (tail : ∀ {u w} (hwu : E.Generates u) (huw' : E.Rewrites u w),
            motive u hwu → motive w (derives_tail hwu huw')) : motive w' t := by
  induction t with
  | refl => exact refl
  | tail x y h => exact tail x y h

end EDT0LGrammar

-- now we get to the main part of this file where we define
-- equivalent EDT0L grammars

namespace EDT0LGrammar

def equivSymbol {α α' V V'} (equivα : α ≃ α') (equivV : V ≃ V') :
    Equiv (Symbol α V) (Symbol α' V') where
  toFun := fun
    | .terminal a => .terminal (equivα a)
    | .nonterminal v => .nonterminal (equivV v)
  invFun := fun
    | .terminal a => .terminal (equivα.symm a)
    | .nonterminal v => .nonterminal (equivV.symm v)
  left_inv := fun | .terminal _ | .nonterminal _ => by simp
  right_inv := fun | .terminal _ | .nonterminal _ => by simp

lemma equivSymbol_symm {α α' V V'} (equivα : α ≃ α') (equivV : V ≃ V') :
    (equivSymbol equivα equivV).symm = equivSymbol equivα.symm equivV.symm := rfl

@[simp]
lemma equivSymbol_compose {α α' α'' V V' V''}
  (equivα : α ≃ α') (equivV : V ≃ V') (equivα' : α' ≃ α'') (equivV' : V' ≃ V'') :
    (equivSymbol equivα' equivV') ∘ (equivSymbol equivα equivV) =
      (equivSymbol (Equiv.trans equivα equivα') (Equiv.trans equivV equivV')) := by
  ext1 x ; cases x <;> rfl

@[simp]
lemma equivSymbol_terminal {α α' V V'} (equivα : α ≃ α') (equivV : V ≃ V') (a) :
    equivSymbol equivα equivV (.terminal a) = .terminal (equivα a) := rfl

@[simp]
lemma equivSymbol_nonterminal {α α' V V'} (equivα : α ≃ α') (equivV : V ≃ V') (v) :
    equivSymbol equivα equivV (.nonterminal v) = .nonterminal (equivV v) := rfl

def equivWord {α α' V V'} (equivα : α ≃ α') (equivV : V ≃ V') :
    Equiv (List (Symbol α V)) (List (Symbol α' V')) where
  toFun := List.map (equivSymbol equivα equivV)
  invFun := List.map (equivSymbol equivα.symm equivV.symm)
  left_inv := by
    intro w
    induction w with
    | nil => rfl
    | cons x xs ih => 
      simp only [List.map_cons, List.cons.injEq, and_true, ih]
      cases x <;> simp [equivSymbol]
  right_inv := by
    intro w
    induction w with
    | nil => rfl
    | cons x xs ih =>
      simp only [List.map_cons, List.cons.injEq, and_true, ih]
      cases x <;> simp [equivSymbol]

@[simp← ]
lemma equivWord_symm {α α' V V'} (equivα : α ≃ α') (equivV : V ≃ V') :
    (equivWord equivα equivV).symm = equivWord equivα.symm equivV.symm := rfl

@[simp]
lemma equivWord_compose {α α' α'' V V' V''}
  (equivα : α ≃ α') (equivV : V ≃ V') (equivα' : α' ≃ α'') (equivV' : V' ≃ V'') :
    (equivWord equivα' equivV') ∘ (equivWord equivα equivV) =
      (equivWord (Equiv.trans equivα equivα') (Equiv.trans equivV equivV')) := by
  ext1 x; simp [equivWord]

@[simp]
lemma equivWord_nil {α α' V V'} (equivα : α ≃ α') (equivV : V ≃ V') :
    equivWord equivα equivV [] = [] := rfl

@[simp]
lemma equivWord_singleton {α α' V V'} (equivα : α ≃ α') (equivV : V ≃ V') (s) :
    equivWord equivα equivV [s] = [equivSymbol equivα equivV s] := rfl

@[simp]
lemma equivWord_cons {α α' V V'} (equivα : α ≃ α') (equivV : V ≃ V') (s sx) :
    equivWord equivα equivV (s::sx) =
      (equivSymbol equivα equivV s)::(equivWord equivα equivV sx) := rfl

@[simp]
lemma equivWord_append {α α' V V'} (equivα : α ≃ α') (equivV : V ≃ V') (u v) :
    equivWord equivα equivV (u ++ v) =
      (equivWord equivα equivV u) ++ (equivWord equivα equivV v) := by
  induction u with
  | nil => simp only [List.nil_append, equivWord_nil]
  | cons x xs ih => simp only [List.cons_append, equivWord_cons, ih]

def equivLanguage {α α'} (equivα : α ≃ α') : Equiv (Language α) (Language α') where
  toFun := fun S ↦ Set.image (List.map equivα) S
  invFun := fun S ↦ Set.image (List.map equivα.symm) S
  left_inv := fun S ↦ by
    simp only [Set.image_image]
    simp only [List.map_map, Equiv.symm_comp_self, List.map_id_fun, id_eq, Set.image_id']
  right_inv := fun S ↦ by
    simp only [Set.image_image]
    simp only [List.map_map, Equiv.self_comp_symm, List.map_id_fun, id_eq, Set.image_id']

@[simp]
lemma equivWord_length {α α' V V'} (equivα : α ≃ α') (equivV : V ≃ V') (u) :
    (equivWord equivα equivV u).length = u.length := by
  simp only [equivWord, Equiv.coe_fn_mk, List.length_map]

@[simp]
lemma equivLanguage_mem_iff {α α'} (equivα : α ≃ α') (L w) :
    w ∈ (equivLanguage equivα L) ↔ ∃ u ∈ L, List.map equivα u = w := by
  unfold equivLanguage
  simp only [Equiv.coe_fn_mk]
  exact Iff.of_eq rfl

@[simp]
lemma equivLanguage_id {α} (L : Language α) : equivLanguage (Equiv.refl α) L = L := by
  unfold equivLanguage
  simp only [Equiv.coe_refl, List.map_id_fun, id_eq, Set.image_id', Equiv.refl_symm,
    Equiv.coe_fn_mk]

/--
Produces an equivalence relation on EDT0L grammars.  This equivalence relation is important for the
proof of `EDT0LGrammar.language_isEDT0L`.
-/
def equiv {α α' V V' T T'} (equivα : α ≃ α') (equivV : V ≃ V') (equivT : T ≃ T') :
    Equiv (EDT0LGrammar α V T) (EDT0LGrammar α' V' T') where
  toFun := fun E ↦ {
    initial := equivV E.initial
    table := fun t v ↦ equivWord equivα equivV (E.table (equivT.symm t) (equivV.symm v)) }
  invFun := fun E ↦ {
    initial := equivV.symm E.initial
    table := fun t v ↦ (equivWord equivα equivV).symm (E.table (equivT t) (equivV v)) }
  left_inv := fun E ↦ by simp only [Equiv.symm_apply_apply]
  right_inv := fun E ↦ by simp only [Equiv.apply_symm_apply]

lemma equiv_symm {α α' V V' T T'} (equivα : α ≃ α') (equivV : V ≃ V') (equivT : T ≃ T') :
    (equiv equivα equivV equivT).symm = equiv equivα.symm equivV.symm equivT.symm := rfl

@[simp]
lemma equiv_initialWord {α α' V V' T T'}
  (equivα : α ≃ α') (equivV : V ≃ V') (equivT : T ≃ T')
  (E : EDT0LGrammar α V T) :
    (equiv equivα equivV equivT E).initialWord = equivWord equivα equivV E.initialWord := rfl

@[simp]
lemma equiv_table {α α' V V' T T'}
  (equivα : α ≃ α') (equivV : V ≃ V') (equivT : T ≃ T')
  (E : EDT0LGrammar α V T) :
    (equiv equivα equivV equivT E).table =
      fun t v ↦ equivWord equivα equivV (E.table (equivT.symm t) (equivV.symm v)) := rfl

@[simp]
lemma equiv_rewriteSymbol {α α' V V' T T'}
  (equivα : α ≃ α') (equivV : V ≃ V') (equivT : T ≃ T')
  (E : EDT0LGrammar α V T) (t s) :
    (equiv equivα equivV equivT E).rewriteSymbol t s =
      equivWord equivα equivV (
        E.rewriteSymbol
          (equivT.symm t)
          ((equivSymbol equivα equivV).symm s)) := by
  cases s
  · simp only [rewriteSymbol_terminal, equivSymbol_symm, equivSymbol_terminal, equivWord_cons,
      Equiv.apply_symm_apply, equivWord_nil]
  · simp only [rewriteSymbol_nonterminal, equiv_table, equivSymbol_symm, equivSymbol_nonterminal]

@[simp]
lemma equiv_rewriteWord {α α' V V' T T'}
  (equivα : α ≃ α') (equivV : V ≃ V') (equivT : T ≃ T')
  (E : EDT0LGrammar α V T) (t w) :
    (equiv equivα equivV equivT E).rewriteWord t w =
      equivWord equivα equivV (
        E.rewriteWord
          (equivT.symm t)
          ((equivWord equivα equivV).symm w)) := by
  induction w with
  | nil => rfl
  | cons x xs ih =>
    simp only [rewriteWord_cons, equiv_rewriteSymbol, equivSymbol_symm, equivWord_symm,
      equivWord_cons, equivWord_append, ih]

@[simp]
lemma equiv_rewrites {α α' V V' T T'}
  (equivα : α ≃ α') (equivV : V ≃ V') (equivT : T ≃ T')
  (E : EDT0LGrammar α V T) (u v) :
    (equiv equivα equivV equivT E).Rewrites u v ↔
      E.Rewrites ((equivWord equivα equivV).symm u) ((equivWord equivα equivV).symm v) := by
  constructor
  · intro h
    obtain ⟨t, rfl⟩ := h
    use (equivT.symm t)
    simp only [equivWord_symm, equiv_rewriteWord]
    exact (Equiv.symm_apply_eq (equivWord equivα.symm equivV.symm)).mp rfl
  · intro h
    obtain ⟨t, h⟩ := h
    use (equivT t)
    simp only [equivWord_symm] at h
    simp only [equiv_rewriteWord, Equiv.symm_apply_apply, equivWord_symm, h]
    exact (Equiv.eq_symm_apply (equivWord equivα equivV)).mp rfl

private lemma equiv_derives_imp {α α' V V' T T'}
  (equivα : α ≃ α') (equivV : V ≃ V') (equivT : T ≃ T')
  (E : EDT0LGrammar α V T) (u v) :
    (equiv equivα equivV equivT E).Derives u v →
      E.Derives ((equivWord equivα equivV).symm u) ((equivWord equivα equivV).symm v) := by
  intro h
  induction h with
  | refl => exact derives_refl
  | tail ih1 ih2 ih3 =>
    rename_i x y
    simp only [equiv_rewrites, equivWord_symm] at ih2
    simp only [equivWord_symm] at ih3
    exact derives_tail ih3 ih2

@[simp]
lemma equiv_derives {α α' V V' T T'}
  (equivα : α ≃ α') (equivV : V ≃ V') (equivT : T ≃ T')
  (E : EDT0LGrammar α V T) (u v) :
    (equiv equivα equivV equivT E).Derives u v ↔
      E.Derives ((equivWord equivα equivV).symm u) ((equivWord equivα equivV).symm v) := by
  constructor
  · exact equiv_derives_imp _ _ _ _ _ _
  · let E' := equiv equivα equivV equivT E
    rw [
      show E = (equiv equivα equivV equivT).symm E' by
        unfold E'
        simp only [Equiv.symm_apply_apply]
    ]
    --
    let u' := (equivWord equivα equivV).symm u
    let v' := (equivWord equivα equivV).symm v
    rw [show u = (equivWord equivα equivV) u' by unfold u'; simp only [Equiv.apply_symm_apply]]
    rw [show v = (equivWord equivα equivV) v' by unfold v'; simp only [Equiv.apply_symm_apply]]
    --
    let equivα' := equivα.symm
    let equivV' := equivV.symm
    rw [show equivα = equivα'.symm by rfl]
    rw [show equivV = equivV'.symm by rfl]
    --
    simp only [Equiv.apply_symm_apply, Equiv.symm_apply_apply]
    simp only [equiv_symm, Equiv.symm_symm]
    --
    conv => rhs; simp only [← equivWord_symm]
    exact equiv_derives_imp _ _ _ _ _ _

@[simp]
lemma equiv_generates {α α' V V' T T'}
  (equivα : α ≃ α') (equivV : V ≃ V') (equivT : T ≃ T')
  (E : EDT0LGrammar α V T) (w) :
    (equiv equivα equivV equivT E).Generates w ↔
      E.Generates ((equivWord equivα equivV).symm w) := by
  unfold Generates 
  have h :
      E.initialWord = ((equivWord equivα equivV).symm (equivWord equivα equivV E.initialWord)) := by
    simp only [Equiv.symm_apply_apply]
  conv => rhs; rw [h]
  exact equiv_derives _ _ _ _ _ _

lemma equiv_language {α α' V V' T T'}
  (equivα : α ≃ α') (equivV : V ≃ V') (equivT : T ≃ T')
  (E : EDT0LGrammar α V T) :
    (equiv equivα equivV equivT E).language = equivLanguage equivα E.language := by
  ext1 x
  simp only [language_mem_iff, equiv_generates, equivWord_symm]
  simp only [equivLanguage_mem_iff, language_mem_iff]
  constructor
  · intro h
    use (List.map equivα.symm x)
    simp only [List.map_map, Equiv.self_comp_symm, List.map_id_fun, id_eq, and_true]
    unfold equivWord equivSymbol at h
    simp only [Equiv.symm_symm, Equiv.coe_fn_mk, List.map_map] at h
    --
    change let f := _; E.Generates (List.map f _) at h
    extract_lets f at h
    --
    change let g := _; E.Generates (List.map g _)
    extract_lets g
    --
    rw [show g = f by unfold f g; funext x; simp only [Function.comp_apply]]
    --
    exact h
  · intro h
    obtain ⟨u, h, rfl⟩ := h
    unfold equivWord equivSymbol
    simp only [Equiv.symm_symm, Equiv.coe_fn_mk, List.map_map]
    --
    change let f := _; E.Generates (List.map f _)
    extract_lets f
    --
    have h' : f = .terminal := by
      unfold f
      funext x
      simp only [Function.comp_apply, Equiv.symm_apply_apply]
    --
    rw [h']
    exact h

@[simp]
theorem equiv_language_eq_language {α V V' T T'}
  (equivV : V ≃ V') (equivT : T ≃ T')
  (E : EDT0LGrammar α V T) :
    (equiv (Equiv.refl α) equivV equivT E).language = E.language := by
  conv => rhs; rw [← equivLanguage_id E.language]
  exact equiv_language (Equiv.refl α) equivV equivT E

protected lemma fin_nonterminals_and_tables {α V T : Type*} [Fintype V] [Fintype T]
  (E : EDT0LGrammar α V T) :
    (E.equiv (Equiv.refl α) (Fintype.equivFin V) (Fintype.equivFin T)).language = E.language :=
  E.equiv_language_eq_language _ _

theorem language_isEDT0L {α V T : Type*} [Finite V] [Finite T] (E : EDT0LGrammar α V T) :
    E.language.IsEDT0L :=
  have := Fintype.ofFinite V
  have := Fintype.ofFinite T
  ⟨_, _, _, E.fin_nonterminals_and_tables⟩

end EDT0LGrammar
