/-
Copyright (c) 2025 Alex Bishop. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Alex Bishop
-/
import Mathlib.Computability.Language
import Mathlib.Computability.DFA
import Mathlib.Data.List.Basic
import Mathlib.Logic.Equiv.Basic
import Mathlib.Logic.Relation

/-!
# EDT0L Grammars

An EDT0L grammar consists of the following data:
 * a finite alphabet of terminal letters `α`;
 * a finite alphabet of nonterminal letters `V`;
 * an initial nonterminal letter; and
 * a finite number of maps of the form `N → List (Symbol α V)` which we refer to as tables.
Notice that `Symbol α V` is a type, provided by Mathlib, which corresponds to a disjoint union
of the types `α` and `V`.

To simplify proofs in this project, we index the tables of the grammar using a finite type `T`.

## Applying tables

Suppose we are given some word `w : List (Symbol α V)`, then we may apply a table of the form
`τ : V → List (Symbol α V)` by replacing each nonterminal in `w` with the corresponding word
given by `τ`, and leaving all the terminal letters along.

Let `E` be an EDT0L grammar. Then, a word `w : List α` is then accepted by the grammar if the word
`w.map Symbol.terminal` can be reached from the initial word `[Symbol.nonterminal E.intial]`
by applying a finite sequence of tables. The set of all such words is known as an EDT0L language.
-/

/-- EDT0L grammar with terminals `α`, nonterminals `V`, and tables `T`. -/
@[ext]
structure EDT0LGrammar (α V T : Type*) [Fintype V] [Fintype T] where
  /-- Initial nonterminal of the grammar -/
  initial : V
  /-- The finite set of tables, as indexed by `T`. -/
  tables : T → V → List (Symbol α V)

namespace EDT0LGrammar
variable {α V T : Type*} [Fintype V] [Fintype T]
variable (E : EDT0LGrammar α V T)
include E

/-- Rewrites a symbol with respect to a given table. -/
def rewriteSymbol (t : T) : Symbol α V → List (Symbol α V)
  | .terminal a => [ .terminal a ]
  | .nonterminal v => E.tables t v

/-- Applies a given table to the given word. -/
def rewriteWord (t : T) (w : List (Symbol α V)) : List (Symbol α V) :=
  w.flatMap (E.rewriteSymbol t)

/-- A relation which holds if there exists a table which rewrites the word
`source` to the word `target`. -/
def rewrites (source target : List (Symbol α V)) : Prop :=
  ∃ t : T, E.rewriteWord t source = target

/-- The reflexive transitive closure of `EDT0LGrammar.Rewrites`. -/
def derives : List (Symbol α V) → List (Symbol α V) → Prop :=
  Relation.ReflTransGen E.rewrites

/-- The given word can be derived from the inital word. -/
def generates (w : List (Symbol α V)) : Prop :=
  E.derives [Symbol.nonterminal E.initial] w

/-- The language produced by the EDT0L grammar -/
def language : Language α := { w : List α | E.generates (w.map Symbol.terminal) }

end EDT0LGrammar

/-- The language is EDT0L.

Notice that this definition requries that the language is generated by an EDT0L language
where the set of nonterminals and terminals are of the form `Fin n` and `Fin m`, respectively,
for some `n m : ℕ`. Our main goal in this file is to show that we can assume without loss of
generality that any given EDT0L grammar is of this form. We prove this fact in the theorem
`edt0l_grammars_generate_edt0l_languages`, at the end of this file. -/
def Language.IsEDT0L {α : Type*} (L : Language α) : Prop :=
  ∃ n m : ℕ, ∃ E : EDT0LGrammar α (Fin n) (Fin m), E.language = L

namespace EDT0LGrammar
variable {α V T : Type*} [Fintype V] [Fintype T]

-- now let's prove some very basic lemmas for `RewriteSymbol`

section RewriteSymbol
variable (E : EDT0LGrammar α V T) (t : T)

@[simp]
lemma rewriteSymbol_terminal (a : α) : E.rewriteSymbol t (.terminal a) = [.terminal a] := rfl

@[simp]
lemma rewriteSymbol_nonterminal (v : V) : E.rewriteSymbol t (.nonterminal v) = E.tables t v := rfl

end RewriteSymbol

-- let's now move on to words

section RewriteWord
variable (E : EDT0LGrammar α V T) (t : T)

@[simp]
lemma rewriteWord_nil : E.rewriteWord t [] = [] := rfl

@[simp]
lemma rewriteWord_cons {x : Symbol α V} {xs : List (Symbol α V)} :
    E.rewriteWord t (x::xs) = (E.rewriteSymbol t x) ++ (E.rewriteWord t xs) := rfl

@[simp]
lemma rewriteWord_append {w₁ w₂ : List (Symbol α V)} :
    E.rewriteWord t (w₁ ++ w₂) = (E.rewriteWord t w₁) ++ (E.rewriteWord t w₂) := List.flatMap_append

@[simp]
lemma rewriteWord_single {x : Symbol α V} :
    E.rewriteWord t [x] = E.rewriteSymbol t x := by
  simp only [rewriteWord_cons, rewriteWord_nil, List.append_nil]

@[simp]
lemma rewriteWord_terminals {w : List α} :
    E.rewriteWord t (w.map .terminal) = (w.map .terminal) := by
  induction w with
  | nil => simp only [List.map_nil, rewriteWord_nil]
  | cons a as ih =>
    simp only [List.map_cons, rewriteWord_cons, rewriteSymbol_terminal, List.cons_append,
      List.nil_append, List.cons.injEq, true_and]
    rw [ih]

end RewriteWord

-- rewrites definition

section Rewrites
variable (E : EDT0LGrammar α V T) (t : T)

lemma rewrites_nil {w : List (Symbol α V)}
  (h : E.rewrites [] w) :
    w = [] := by
  obtain ⟨τ, rfl⟩ := h
  simp only [rewriteWord_nil]

lemma rewrites_terminals {w : List α} {w' : List (Symbol α V)}
  (h : E.rewrites (w.map .terminal) w') :
    w' = (w.map .terminal) := by
  replace ⟨τ,h⟩ := h
  simp only [rewriteWord_terminals] at h
  rw [← h]

end Rewrites

-- The following namespace contains proofs that Derives is reflexive and transitive
-- and the corresponding type class instanciations. These type classes are needed if
-- you want to use the `calc` tactic.

section Derives
section lemmas_for_derives
variable {x y z : List (Symbol α V)}
variable {E : EDT0LGrammar α V T}

lemma derives_trans (h₁ : E.derives x y) (h₂ : E.derives y z) : E.derives x z :=
  Relation.ReflTransGen.trans h₁ h₂

lemma derives_single (h : E.rewrites x y) : E.derives x y :=
  Relation.ReflTransGen.single h

lemma derives_head (h₁ : E.rewrites x y) (h₂ : E.derives y z) : E.derives x z :=
  Relation.ReflTransGen.head h₁ h₂

lemma derives_tail (h₁ : E.derives x y) (h₂ : E.rewrites y z) : E.derives x z :=
  Relation.ReflTransGen.tail h₁ h₂

lemma derives_refl : E.derives x x :=
  Relation.ReflTransGen.refl

end lemmas_for_derives

section class_instances_for_derives
variable (E : EDT0LGrammar α V T)

instance : Trans E.derives E.derives E.derives where
  trans h₁ h₂ := derives_trans h₁ h₂

instance : Trans E.derives E.rewrites E.derives where
  trans h₁ h₂ := derives_tail h₁ h₂

instance : Trans E.rewrites E.derives E.derives where
  trans h₁ h₂ := derives_head h₁ h₂

instance : Trans E.rewrites E.rewrites E.derives where
  trans h₁ h₂ := derives_tail (derives_single h₁) h₂

instance : IsTrans (List (Symbol α V)) E.derives where
  trans _ := fun _ _ hxy hyz ↦ derives_trans hxy hyz

instance : IsRefl (List (Symbol α V)) E.derives where
  refl _ := derives_refl

instance : IsPreorder (List (Symbol α V)) E.derives where
  trans _ := fun _ _ hxy hyz ↦ derives_trans hxy hyz
  refl _ := derives_refl

end class_instances_for_derives
end Derives

-- some additional lemmas about derives

section Derives
variable (E : EDT0LGrammar α V T)

lemma derives_nil {w : List (Symbol α V)}
  (h : E.derives [] w) :
    w = [] := by
  induction h with
  | refl => rfl
  | tail h_a hab ha =>
    rename_i a b
    subst ha
    exact rewrites_nil E hab

lemma derives_terminals {w : List α} {w' : List (Symbol α V)}
  (h : E.rewrites (w.map .terminal) w') :
    w' = (w.map .terminal) := by
  replace ⟨τ,h⟩ := h
  simp only [rewriteWord_terminals] at h
  rw [← h]

end Derives

-- generates

section Generates
variable (E : EDT0LGrammar α V T) in
lemma generates_initial : E.generates [.nonterminal E.initial] := Relation.ReflTransGen.refl
end Generates

end EDT0LGrammar

-- now we get to the main part of this file where we define
-- equivalent EDT0L grammars

namespace EDT0LGrammar

/-- Defines an equivalent EDT0L grammar.

This structure holds the data needed to construct an EDT0L grammar which can be used in the
proof of `edt0l_grammars_generate_edt0l_languages`. We provide this construction as its own
structure as this construction is to be reused when defining EDT0L grammars with finite index -/
structure EquivData {α V T V' T' : Type*} [Fintype V] [Fintype T] [Fintype V'] [Fintype T'] where
  /-- The grammar for which we want to find an equivalent grammar. -/
  E : EDT0LGrammar α V T
  /-- An equivalence relation between nonterminals. -/
  equivV : V ≃ V'
  /-- An equivalence relation between tables. -/
  equivT : T ≃ T'

namespace EquivData
variable {α V T V' T' : Type*} [Fintype V] [Fintype T] [Fintype V'] [Fintype T'] 
variable (data : @EquivData α V T V' T' _ _ _ _)

def equivTableSeq : List T ≃ List T' where
  toFun := fun x ↦ x.map data.equivT
  invFun := fun x ↦ x.map data.equivT.symm
  left_inv := by
    intro s
    simp only [List.map_map, Equiv.symm_comp_self, List.map_id_fun, id_eq]
  right_inv := by
    intro s
    simp only [List.map_map, Equiv.self_comp_symm, List.map_id_fun, id_eq]

@[simp]
lemma equivTableSeq_nil :
    data.equivTableSeq [] = [] := by
  unfold equivTableSeq
  simp only [Equiv.coe_fn_mk, List.map_nil]

@[simp]
lemma equivTableSeq_cons (t ts) :
    data.equivTableSeq (t::ts) = data.equivT t :: (data.equivTableSeq ts) := by
  unfold equivTableSeq
  simp only [Equiv.coe_fn_mk, List.map_cons]

@[simp]
lemma equivTableSeq_append (a b) :
    data.equivTableSeq (a ++ b) = data.equivTableSeq a ++ data.equivTableSeq b := by
  induction a with
  | nil =>
    simp only [List.nil_append, equivTableSeq_nil]
  | cons a as ih =>
    simp only [List.cons_append, equivTableSeq_cons, ih]

@[simp]
lemma equivTableSeq_grammar_nil :
    data.equivTableSeq.symm [] = [] := by
  unfold equivTableSeq
  simp only [Equiv.coe_fn_symm_mk, List.map_nil]

@[simp]
lemma equivTableSeq_grammar_cons (t ts) :
    data.equivTableSeq.symm (t::ts) = data.equivT.symm t :: (data.equivTableSeq.symm ts) := by
  unfold equivTableSeq
  simp only [Equiv.coe_fn_symm_mk, List.map_cons]

@[simp]
lemma equivTableSeq_grammar_append (a b) :
    data.equivTableSeq.symm (a ++ b) = data.equivTableSeq.symm a ++ data.equivTableSeq.symm b := by
  induction a with
  | nil =>
    simp only [List.nil_append, equivTableSeq_grammar_nil]
  | cons a as ih =>
    simp only [List.cons_append, equivTableSeq_grammar_cons, ih]

@[simp]
lemma equivTableSeq_length (a) :
    (data.equivTableSeq a).length = a.length := by
  induction a with
  | nil =>
    simp only [equivTableSeq_nil, List.length_nil]
  | cons a as ih =>
    simp only [equivTableSeq_cons, List.length_cons, ih]

@[simp]
lemma equivTableSeq_length' (a) :
    (data.equivTableSeq.symm a).length = a.length := by
  induction a with
  | nil =>
    simp only [equivTableSeq_grammar_nil, List.length_nil]
  | cons a as ih =>
    simp only [equivTableSeq_grammar_cons, List.length_cons, ih]

/-- An equivalence relation between symbols of terminals and nonterminals.

This equivalence relation is constructed from the equivalence relation between
nonterminals, as stored in the `EquivData` structure. -/
def equivSymbol : (Symbol α V) ≃ (Symbol α V') where
  toFun := fun x ↦ match x with
    | .terminal a => .terminal a
    | .nonterminal v => .nonterminal (data.equivV v)
  invFun := fun x ↦ match x with
    | .terminal a => .terminal a
    | .nonterminal v => .nonterminal (data.equivV.symm v)
  left_inv := by
    intro x
    cases x
    · rfl
    · simp_all only [Equiv.symm_apply_apply]
  right_inv := by
    intro x
    cases x
    · rfl
    · simp_all only [Equiv.apply_symm_apply]


/-- An equivalence relation between words.

This equivalence relation is constructed from the equivalence relation between
nonterminals, as stored in the `EquivData` structure. -/
def equivWord : List (Symbol α V) ≃ List (Symbol α V') where
  toFun := List.map data.equivSymbol
  invFun := List.map data.equivSymbol.symm
  left_inv := by
    intro x
    simp_all only [
      List.map_map,
      Equiv.symm_comp_self,
      List.map_id_fun,
      id_eq]
  right_inv := by
    intro x
    simp_all only [
      List.map_map,
      Equiv.self_comp_symm,
      List.map_id_fun,
      id_eq]

/-- Constructs an EDT0L grammar equivalent to the one store in `EquivData`. -/
def grammar : EDT0LGrammar α V' T' where
  initial := data.equivV data.E.initial
  tables := fun t v ↦ data.equivWord (data.E.tables (data.equivT.symm t) (data.equivV.symm v))

@[simp]
lemma equivSymbol_terminal {a : α} : data.equivSymbol (.terminal a) = .terminal a := rfl

@[simp]
lemma equiv_symbol_nonterminal {v : V} :
    data.equivSymbol (.nonterminal v) = .nonterminal (data.equivV v) := rfl

@[simp]
lemma equiv_symbol_nonterminal' {v} :
    data.equivSymbol.symm (.nonterminal v) = .nonterminal (data.equivV.symm v) := rfl

@[simp]
lemma equivV_initial :
    data.equivV data.E.initial = data.grammar.initial := by
  unfold EquivData.grammar
  simp only

@[simp]
lemma equivV_grammar_initial :
    data.equivV.symm data.grammar.initial = data.E.initial := by
  unfold EquivData.grammar
  simp only [Equiv.symm_apply_apply]

@[simp]
lemma equivWord_nil : data.equivWord [] = [] := rfl

@[simp]
lemma equivWord_singleton {x : Symbol α V} : data.equivWord [x] = [data.equivSymbol x] := rfl

@[simp]
lemma equivWord_cons {x : Symbol α V} {xs : List (Symbol α V)} :
    data.equivWord (x::xs) = (data.equivSymbol x) :: (data.equivWord xs) := rfl

@[simp]
lemma equivWord_append {x y : List (Symbol α V)} :
    data.equivWord (x ++ y) = (data.equivWord x) ++ (data.equivWord y) := by
  induction x with
  | nil => simp only [List.nil_append, equivWord_nil]
  | cons a as ih =>
    simp only [List.cons_append, equivWord_cons, List.cons.injEq, true_and]
    rw [← ih]

@[simp]
lemma equivWord_terminals {w : List α} :
    data.equivWord (w.map .terminal) = w.map .terminal := by
  induction w with
  | nil =>
    unfold equivWord
    simp only [List.map_nil, Equiv.coe_fn_mk]
  | cons a as ih =>
    simp only [List.map_cons, equivWord_cons, equivSymbol_terminal, List.cons.injEq, true_and]
    rw [← ih]

def symm := EquivData.mk data.grammar data.equivV.symm data.equivT.symm

lemma symm_equivSymbol : data.symm.equivSymbol = data.equivSymbol.symm := rfl

lemma symm_equivWord : data.symm.equivWord = data.equivWord.symm := rfl

@[simp]
lemma equivWord_symm_nil : data.equivWord.symm [] = [] := rfl

@[simp]
lemma equivWord_symm_single {x : Symbol α V'} :
    data.equivWord.symm [x] = [data.equivSymbol.symm x] := rfl

@[simp]
lemma equivWord_symm_cons {x : Symbol α V'} {xs : List (Symbol α V')} :
    data.equivWord.symm (x::xs) = (data.equivSymbol.symm x) :: (data.equivWord.symm xs) := rfl

@[simp]
lemma equivWord_symm_append {x y : List (Symbol α V')} :
    data.equivWord.symm (x ++ y) = (data.equivWord.symm x) ++ (data.equivWord.symm y) := by
  induction x with
  | nil => simp only [List.nil_append, equivWord_symm_nil]
  | cons a as ih =>
    simp only [List.cons_append, equivWord_symm_cons, List.cons.injEq, true_and]
    rw [← ih]

@[simp]
lemma equivWord_symm_terminals {w : List α} :
    data.equivWord.symm (w.map .terminal) = w.map .terminal := by
  induction w with
  | nil =>
    unfold equivWord
    simp only [List.map_nil, Equiv.coe_fn_symm_mk]
  | cons a as ih =>
    simp only [List.map_cons, equivWord_symm_cons, List.cons.injEq]
    rw [← ih]
    simp only [and_true]
    rfl

@[simp]
lemma symm_grammar : data.symm.grammar = data.E := by
  ext1
  · unfold EquivData.symm
    unfold EquivData.grammar
    simp only [Equiv.symm_apply_apply]
  · unfold EquivData.symm
    unfold EquivData.grammar
    simp only [Equiv.symm_symm, Equiv.symm_apply_apply]
    funext h n
    change data.symm.equivWord _ = _
    simp only [symm_equivWord, Equiv.symm_apply_apply]

@[simp]
lemma grammar_rewriteSymbol_iff {t : T'} {x : Symbol α V'} :
    data.grammar.rewriteSymbol t x
    = data.equivWord (
        data.E.rewriteSymbol
          (data.equivT.symm t)
          (data.equivSymbol.symm x)) := by
  unfold EDT0LGrammar.rewriteSymbol
  split <;> rfl

@[simp]
lemma grammar_rewriteWord_iff {t : T'} {w : List (Symbol α V')} :
    data.grammar.rewriteWord t w
    = data.equivWord (
        data.E.rewriteWord
          (data.equivT.symm t)
          (data.equivWord.symm w)) := by
  --
  unfold EDT0LGrammar.rewriteWord
  induction w with
  | nil =>
    simp only [List.flatMap_nil, List.nil_eq]
    rfl
  | cons a as ih =>
    conv =>
      right ; arg 2 ; arg 2
      simp only [← symm_equivWord, equivWord_cons, symm_equivWord]
    simp only [List.flatMap_cons]
    conv =>
      right
      simp only [← symm_equivWord, equivWord_append, symm_equivWord]
    rw [ih]
    simp only [grammar_rewriteSymbol_iff, equivWord_symm_cons, List.flatMap_cons, equivWord_append]

@[simp]
lemma grammar_rewrites_iff (x y : List (Symbol α V')) :
    data.grammar.rewrites x y
      ↔ data.E.rewrites (data.equivWord.symm x) (data.equivWord.symm y) := by
  --
  constructor
  · unfold EDT0LGrammar.rewrites
    intro h
    have ⟨t, h'⟩ := h
    use (data.equivT.symm t)
    rw [grammar_rewriteWord_iff] at h'
    rw [← h']
    simp only [Equiv.symm_apply_apply]
  · unfold EDT0LGrammar.rewrites
    intro h
    have ⟨t, h'⟩ := h
    use (data.equivT t)
    rw [grammar_rewriteWord_iff]
    conv =>
      arg 1 ; arg 2 ; arg 2
      simp only [Equiv.invFun_as_coe, Equiv.toFun_as_coe, Equiv.symm_apply_apply]
    rw [h']
    simp only [Equiv.apply_symm_apply]

lemma grammar_derives_iff_mp (x y : List (Symbol α V')) :
    data.grammar.derives x y → data.E.derives (data.equivWord.symm x) (data.equivWord.symm y) := by
  --
  unfold EDT0LGrammar.derives
  intro h
  induction h with
  | refl =>
    rw [Relation.reflTransGen_iff_eq_or_transGen]
    left
    rfl
  | tail ih₁ ih₂ ih₃ =>
    rename_i a b
    replace ih₂ := (grammar_rewrites_iff data a b).mp ih₂
    exact Relation.ReflTransGen.tail ih₃ ih₂

lemma grammar_derives_iff_mpr (x y : List (Symbol α V')) :
    data.E.derives (data.equivWord.symm x) (data.equivWord.symm y) → data.grammar.derives x y := by
  --
  simp only [← symm_grammar]
  intro h
  have hh :=
    grammar_derives_iff_mp
      (EquivData.mk (data.grammar) (data.equivV.symm) (data.equivT.symm))
      (data.equivWord.symm x) (data.equivWord.symm y)
      h
  conv at hh =>
    arg 2
    change data.equivWord _
    simp only [Equiv.invFun_as_coe, Equiv.toFun_as_coe, Equiv.apply_symm_apply]
  conv at hh =>
    arg 3
    change data.equivWord _
    simp only [Equiv.invFun_as_coe, Equiv.toFun_as_coe, Equiv.apply_symm_apply]
  exact hh

lemma grammar_derives_iff {x y : List (Symbol α V')} :
    data.grammar.derives x y ↔ data.E.derives (data.equivWord.symm x) (data.equivWord.symm y) := by
  constructor
  · exact grammar_derives_iff_mp _ _ _
  · exact grammar_derives_iff_mpr _ _ _

lemma grammar_derives_iff' {x y : List (Symbol α V)} :
    data.E.derives x y ↔ data.grammar.derives (data.equivWord x) (data.equivWord y) := by
  simp only [← symm_grammar]
  exact grammar_derives_iff _

lemma grammar_generates_iff {w : List (Symbol α V)} :
    data.E.generates w ↔ data.grammar.generates (data.equivWord w) := grammar_derives_iff' _

lemma grammar_language_iff {w : List α} :
    data.E.generates (List.map .terminal w) ↔ data.grammar.generates (List.map .terminal w) := by
  conv =>
    rhs; arg 2
    rw [← equivWord_terminals data]
  exact grammar_generates_iff _

@[simp]
lemma equiv_eq_language : data.E.language = data.grammar.language := by
  unfold EDT0LGrammar.language
  simp only [grammar_language_iff]

end EquivData

lemma fin_nonterminals_and_tables {α V T : Type*} [finV : Fintype V] [finT : Fintype T]
  (E : EDT0LGrammar α V T) :
    ∃ E' : EDT0LGrammar α (Fin (Fintype.card V)) (Fin (Fintype.card T)),
      E'.language = E.language := by 
  --
  have isoV := finV.equivFin
  have isoT := finT.equivFin
  let E' := EquivData.mk E isoV isoT
  use E'.grammar
  conv =>
    rhs
    change E'.E.language
  apply Eq.symm
  exact EquivData.equiv_eq_language _

theorem edt0l_grammars_generate_edt0l_languages {α V T : Type*} [Fintype V] [Fintype T]
  (E : EDT0LGrammar α V T) :
    E.language.IsEDT0L := by
  --
  have ⟨E', h⟩ := fin_nonterminals_and_tables E
  unfold Language.IsEDT0L
  use Fintype.card V, Fintype.card T, E'

end EDT0LGrammar
