/-
Copyright (c) 2025 Alex Bishop. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Alex Bishop
-/
module

public import LSystems.EDT0L.Defs
public import LSystems.EDT0L.Basic
public import LSystems.EDT0L.RewriteSequence

/-!
# LULT Grammar

An EDT0L language is called *LULT* if, for every word generated by the grammar, there exists some
derivation sequence such that, at each step, and for each nonterminal `v` either:
* the nonterminal `v` appears at most once in the step of the derivation; or
* the nonterminal `v` contributes a word of length at most 1 to the final output.

## Main definitions

* `EDT0LGrammar.IsLULT`
  a predicate indicating that a given word is LULT
* `Language.IsLULT`
  A predicate indicating that a language is generated by a LULT grammar

## Main theorems

* `EDT0LGrammar.lult_language_isLULT`
  The language generated by a LULT grammar is itself LULT
-/

@[expose] public section

namespace EDT0LGrammar

def IsLULT {α V T : Type*} [BEq V] (E : EDT0LGrammar α V T) : Prop :=
  ∀ w ∈ E.language,
    ∃ (s : List T),
      E.rewriteSeq s E.initialWord = w.map .terminal ∧
      ∀ (v : V) (i : ℕ),
        i ≤ s.length →
          (filterNonterminals (E.rewriteSeq (s.take i) E.initialWord)).count v ≤ 1 ∨
          (E.rewriteSeq (s.drop i) [.nonterminal v]).length ≤ 1

end EDT0LGrammar

def Language.IsLULT {α : Type*} (L : Language α) : Prop :=
  ∃ n m : ℕ, ∃ E : EDT0LGrammar α (Fin n) (Fin m), E.IsLULT ∧ E.language = L

namespace EDT0LGrammar
variable {α V T : Type*} [BEq V] [LawfulBEq V] (E : EDT0LGrammar α V T)

private lemma equiv_isLULT {α' V' T'} [BEq V'] [LawfulBEq V']
  (equivα : α ≃ α') (equivV : V ≃ V') (equivT : T ≃ T')
  (h : E.IsLULT) :
    (E.equiv equivα equivV equivT).IsLULT := by
  classical
  intro w hw
  have ⟨s, h', h''⟩ := h (w.map equivα.symm) (by
    rw [equiv_language] at hw
    obtain ⟨w', hw, rfl⟩ := hw
    simpa )
  --
  use s.map equivT
  constructor
  · simp only [equiv_initialWord, equivWord_cons, equivSymbol_nonterminal, equivWord_nil,
      equiv_rewriteSeq', List.map_map, Equiv.symm_comp_self, List.map_id_fun, id_eq,
      ← equivWord_symm]
    conv =>
      lhs
      arg 2
      unfold equivWord
      simp only [Equiv.symm_mk, Equiv.coe_fn_mk, List.map_cons, equivSymbol_nonterminal,
        Equiv.symm_apply_apply, List.map_nil]
      arg 3
      change E.initialWord
    rw [h']
    unfold equivWord
    simp
  · intro v' i' hi'
    replace h'' := h'' (equivV.symm v') i' (by simp_all)
    obtain h'' | h'' := h''
    · left
      clear * - h''
      simp only [equiv_initialWord, equivWord_cons, equivSymbol_nonterminal, equivWord_nil,
        equiv_rewriteSeq', List.map_take, List.map_map, Equiv.symm_comp_self, List.map_id_fun,
        id_eq, ← equivWord_symm, filterNonterminals_equivWord]
      unfold equivWord
      conv =>
        lhs ; arg 2; arg 2; arg 1; arg 3
        simp only [Equiv.symm_mk, Equiv.coe_fn_mk, List.map_cons, equivSymbol_nonterminal,
          Equiv.symm_apply_apply, List.map_nil]
        change E.initialWord
      rw [List.count, List.countP_map]
      change let f : _ → _ := _ ; List.countP f _ ≤ _
      intro f
      have : f = fun x ↦ x == equivV.symm v' := by
        funext x
        subst f
        clear * -
        simp only [Function.comp_apply, beq_eq_beq]
        exact Iff.symm (Equiv.eq_symm_apply equivV)
      rw [this]
      change List.count _ _ ≤ _
      exact h''
    · right
      clear * - h''
      simpa

lemma equiv_isLULT_iff {α' V' T'} [BEq V'] [LawfulBEq V']
  (equivα : α ≃ α') (equivV : V ≃ V') (equivT : T ≃ T') :
    E.IsLULT ↔ (E.equiv equivα equivV equivT).IsLULT := by
  classical
  constructor
  · exact equiv_isLULT E equivα equivV equivT
  · let E' := (equiv equivα equivV equivT) E
    have h' : E = (equiv equivα.symm equivV.symm equivT.symm) E' :=
      (Equiv.symm_apply_eq (equiv equivα.symm equivV.symm equivT.symm)).mp rfl
    conv => intro x ; rw [h']
    change E'.IsLULT → _
    exact equiv_isLULT E' equivα.symm equivV.symm equivT.symm

theorem lult_language_isLULT [Finite V] [Finite T] :
    E.IsLULT → E.language.IsLULT := by
  intro h
  have := Fintype.ofFinite V
  have := Fintype.ofFinite T
  have h' := equiv_language_eq_language (Fintype.equivFin V) (Fintype.equivFin T) E
  unfold Language.IsLULT
  exact ⟨_, _ , _,  equiv_isLULT E (Equiv.refl α) _ _ h, h'⟩

end EDT0LGrammar
