/-
Copyright (c) 2025 Alex Bishop. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Alex Bishop
-/
module

public import LSystems.FiniteIndexEDT0L.Defs
public import LSystems.FiniteIndexEDT0L.LULT.Defs

public import Mathlib.Data.Finset.Lattice.Fold
public import Mathlib.Data.Fintype.Pi

import LSystems.FiniteIndexEDT0L.LULT.Attach
import LSystems.FiniteIndexEDT0L.Attach
import LSystems.FiniteIndexEDT0L.Mapped

/-!
# LULT implies Finite-Index EDT0L

It it known in the lterature that if a formal languagaue is LULT, then it can be generated by an
EDT0L grammar with finite index.  In this file, we give a constructive proof of this result.
-/

@[expose] public section

namespace EDT0LGrammar
namespace LULT2EDT0L

/--
Recall that in the definition of a LULT grammar that, for each word `w` which is generatd by the
grammar, there must exist `S → w_1 → w_2 → ⋯ → w_k → w` where each sentential form `w_j` in the
path has the following property:

 > For each nonterminal `n`, either `n` occurs at most once in `w_i`, or the each nonterminal `n` in
 > the sentential form will contribute a word of length at most 1 to the output word `w`.

This type is used to represent these two cases.  Note here that `α` should be understood to be type
of the terminal letters of the LULT grammar.
-/
inductive Guess (α : Type*) where
  /-- Corresponds to a nonterminal which appears at most once in a sentential form, and for which
  we don't a priori know how much it contributes. -/
  | unknown
  /-- Corresponds to a nonterminal which contributes only an empty word to the output. -/
  | empty
  /-- Corresponds to a nonterminal which contributes a single letter to the output word. -/
  | single (a : α)
deriving Fintype, DecidableEq

def Guess.toList? {α} (guess : Guess α) : Option (List α) :=
  match guess with
  | .unknown => none
  | .empty => some []
  | .single a => some [a]

def Guess.toList {α} (guess : Guess α) (h : guess ≠ .unknown) : List α :=
  match guess with
  | .unknown => nomatch (h rfl)
  | .empty => []
  | .single a => [a]

abbrev GuessList (α V) := V → Guess α

/--
During the application of our constructed grammar, we will need to keep track of what we have
`guessed` a given nonterminal will become in the output word.  We hold this data in this type.

Here:
  * `α` is the terminal alphabet; and
  * `V` is the nonterminal alphabet.
-/
@[ext]
structure State (α V : Type*) [Fintype V] where
  /-- The number of nonterminals which appear in a given sentential form of our contructed grammar.
  Note that you should make use of the `State.length` and `State.length_prop` functions instead of
  accessing this value directly. -/
  finLength : Fin (Fintype.card V + 1)
  /-- The nonterminals which actually appear in the sentential form, in the order they actually
  appear. -/
  get' : Fin finLength.val → V
  /-- In our construction, we intent to create a finite-index EDT0L grammar where each nonterminal
  appears at most once in any given sentential form.  We ensure this by requiring `inj'` to be
  injective. -/
  inj' : Function.Injective get'
  /-- What we guess each nonterminal will contribute to the final output word. -/
  guesses : GuessList α V
  /-- We will require that if a nonterminal appears in a sentential word, then we should not have a
  guess for its contribution.  If we did have a guess, then we should have expanded the nonterminal
  to this guess rather then include it in the sentential form. -/
  guesses_prop' : ∀ i, guesses (get' i) = .unknown

def State.empty {α V} [Fintype V] : State α V where
  finLength := 0
  get' := fun x ↦ nomatch (((inferInstance : IsEmpty (Fin 0)).elim x) : False)
  inj' := fun x _ _ ↦ nomatch (((inferInstance : IsEmpty (Fin 0)).elim x) : False)
  guesses := fun _ ↦ .unknown
  guesses_prop' := fun _ ↦ rfl

def State.length {α V} [Fintype V] (state : State α V) : ℕ := state.finLength.val

lemma State.length_prop {α V} [Fintype V] (state : State α V) : state.length < Fintype.card V + 1 :=
  state.finLength.prop

def State.get {α V} [Fintype V] (state : State α V) : Fin (state.length) → V :=
  fun x ↦ state.get' x

lemma State.inj {α V} [Fintype V] (state : State α V) : Function.Injective state.get := state.inj'

lemma State.guesses_prop {α V} [Fintype V] (state : State α V) :
    ∀ i, state.guesses (state.get i) = .unknown := state.guesses_prop'

def State.toList {α V} [Fintype V] (state : State α V) : List V := List.ofFn state.get

lemma State.toList_nodup {α V} [Fintype V] (state : State α V) : state.toList.Nodup :=
  List.nodup_ofFn_ofInjective (state.inj)

lemma State.toList_length {α V} [Fintype V] (state : State α V) :
    state.toList.length = state.length := List.length_ofFn

instance (α V : Type*) [Fintype V] [DecidableEq α] [DecidableEq V] :
    DecidableEq (State α V) := fun x y ↦
  if h : x.finLength = y.finLength then
    have : (Fin ↑y.finLength → V) = (Fin ↑x.finLength → V) :=
      implies_congr_left (congrArg Fin (congrArg Fin.val (id (Eq.symm h))))
    if h' : x.get' = cast this y.get' then
      if h'' : x.guesses = y.guesses then
        isTrue (by
          ext1
          · exact h
          · exact HEq.symm (heq_of_eqRec_eq this (id (Eq.symm h')))
          · exact h''
          )
      else
        isFalse (fun a ↦ (iff_false_intro h'').mp (congrArg State.guesses a))
    else
      isFalse (fun a ↦ h' (eq_cast_iff_heq.mpr (congr_arg_heq State.get' a)))
  else
    isFalse (fun a ↦ h (congrArg State.finLength a))

instance (α V : Type*) [finα : Fintype α] [finV : Fintype V] [DecidableEq α] [DecidableEq V] :
    Fintype (State α V) where
  elems :=
    Fintype.elems.sup fun (finLength : Fin (Fintype.card V + 1)) ↦
    Fintype.elems.sup fun (get' : Fin finLength.val → V) ↦
    Fintype.elems.sup fun (guesses : V → Guess α) ↦
    if inj' : Function.Injective get' then
      if guesses_prop' : ∀ i, guesses (get' i) = .unknown then
        {⟨finLength, get', inj', guesses, guesses_prop'⟩}
      else
        ∅
    else
      ∅
  complete := by
    intro x
    simp only [Finset.mem_sup]
    use x.finLength, Fintype.complete _
    use x.get', Fintype.complete _
    use x.guesses, Fintype.complete _
    simp [x.inj', x.guesses_prop']

/--
A nonterminal word in the finite-index EDT0L grammar which we are constructing.

Here:
  * `α` is the terminal alphabet of the LULT grammar; and
  * `V` is the nonetrminal alphabet of the LULT grammar.
-/
inductive Nonterminal (α V : Type*) [Fintype V] where
  /-- The initial nonterminal of the EDT0L grammar -/
  | init
  /--
  A dead-end nonterminal.

  Once a sentential form contains this nonterminal, then it can no longer go on to accept anything.
  We seee later that we deign the grammar to ensure that dead nonterminals are never erased.
  -/
  | dead
  /--
  This is a nonterminal which appears exclusively as the first letter in certain sentential forms.
  The purpose of such nonterminals is to simply carry information about the word and to prevent a
  word from being accepted if some invalid guess exists in the `state`.
  -/
  | starter (state : State α V)
  /--
  This word corresponds to a single nonterminal in the associated LULT grammar.  Each such
  nonterminal is labeled with the state of the word, and the index of the letetr into the states.
  -/
  | regular (state : State α V) (i : Fin state.length)
deriving DecidableEq

instance (α V : Type*) [Fintype α] [Fintype V] [DecidableEq α] [DecidableEq V] :
    Fintype (Nonterminal α V) where
  elems :=
    {.init, .dead} ∪
    Fintype.elems.sup fun (state : State α V) ↦
    {.starter state} ∪
    Fintype.elems.sup fun (i : Fin state.length) ↦
    {.regular state i}
  complete := by
    intro x
    simp only [Finset.sup_singleton_apply, Finset.singleton_union, Finset.insert_union,
      Finset.mem_insert, Finset.mem_sup, Finset.mem_image]
    cases x with
    | init | dead => simp
    | starter state =>
      right ; right
      use state, Fintype.complete _
      left
      rfl
    | regular state i =>
      right ; right
      use state, Fintype.complete _
      right
      use i, Fintype.complete _

inductive Table (α V T : Type*) [Fintype V] where
  | init
  | finish
  | step (t : T) (target_state : State α V)
deriving DecidableEq

instance (α V T : Type*)
  [Fintype α] [Fintype V] [Fintype T]
  [DecidableEq α] [DecidableEq V] [DecidableEq T] :
    Fintype (Table α V T) where
  elems :=
    {.init, .finish} ∪
    Fintype.elems.sup fun (t : T) ↦
    Fintype.elems.sup fun (target_state : State α V) ↦
    {.step t target_state}
  complete := by
    intro x
    simp only [Finset.sup_singleton_apply, Finset.insert_union, Finset.singleton_union,
      Finset.mem_insert, Finset.mem_sup, Finset.mem_image]
    cases x with
    | init | finish => simp
    | step t target_state =>
      right; right
      use t, Fintype.complete _
      use target_state, Fintype.complete _


def unlabelSententialWord {α V} [Fintype V] :
    List (Symbol α (Nonterminal α V)) → List (Symbol α V) :=
  List.filterMap fun x ↦
    match x with
    | .terminal a => .some (.terminal a)
    | .nonterminal x =>
      match x with
      | .regular state i => .some (.nonterminal (state.get i))
      | .init | .dead | .starter _ => .none

@[simp]
lemma unlabelSententialWord_nil {α V} [Fintype V] :
    unlabelSententialWord ([] : List (Symbol α (Nonterminal α V))) = [] := rfl

@[simp]
lemma unlabelSententialWord_cons_terminal {α V} [Fintype V]
  (x : α) (xs : List (Symbol α (Nonterminal α V))) :
    unlabelSententialWord (.terminal x::xs) = .terminal x :: unlabelSententialWord xs :=
  List.filterMap_cons_some rfl

@[simp]
lemma unlabelSententialWord_cons_nonterminal {α V} [Fintype V]
  (x : Nonterminal α V) (xs : List (Symbol α (Nonterminal α V))) :
    unlabelSententialWord (.nonterminal x::xs) =
    match x with
      | .regular state i => .nonterminal (state.get i)::unlabelSententialWord xs
      | .init | .dead | .starter _ => unlabelSententialWord xs := by
  split <;> rfl

@[simp]
lemma unlabelSententialWord_append {α V} [Fintype V]
  (a b : List (Symbol α (Nonterminal α V))) :
    unlabelSententialWord (a ++ b) = unlabelSententialWord a ++ unlabelSententialWord b :=
  List.filterMap_append

namespace GuessList

def rewriteSymbol {α V} (guesses : GuessList α V) : Symbol α V → List (Symbol α V)
  | .terminal a =>
      [.terminal a]
  | .nonterminal v =>
      match guesses v with
      | .unknown => [.nonterminal v]
      | .single a => [.terminal a]
      | .empty => []

@[simp]
lemma rewriteSymbol_terminal {α V} (guesses : GuessList α V) {a : α} :
    guesses.rewriteSymbol (.terminal a) = [.terminal a] := rfl

@[simp]
lemma rewriteSymbol_nonterminal_unknown {α V} (guesses : GuessList α V) {v : V} :
    guesses v = .unknown ↔ guesses.rewriteSymbol (.nonterminal v) = [.nonterminal v] := ⟨
  by
    intro h
    unfold rewriteSymbol
    simp [h],
  by
    intro h
    unfold rewriteSymbol at h
    simp only at h
    split at h <;> simp_all ⟩

@[simp]
lemma rewriteSymbol_nonterminal_single {α V} (guesses : GuessList α V) {v : V} {a : α} :
    guesses v = .single a ↔ guesses.rewriteSymbol (.nonterminal v) = [.terminal a] := ⟨
  by
    intro h
    unfold rewriteSymbol
    simp [h],
  by
    intro h
    unfold rewriteSymbol at h
    simp only at h
    split at h <;> simp_all ⟩

@[simp]
lemma rewriteSymbol_nonterminal_empty {α V} (guesses : GuessList α V) {v : V} :
    guesses v = .empty ↔ guesses.rewriteSymbol (.nonterminal v) = [] := ⟨
  by
    intro h
    unfold rewriteSymbol
    simp [h],
  by
    intro h
    unfold rewriteSymbol at h
    simp only at h
    split at h <;> simp_all ⟩

def rewriteWord {α V} (guesses : GuessList α V) : List (Symbol α V) → List (Symbol α V) :=
  List.flatMap (rewriteSymbol guesses)

@[simp]
lemma rewriteWord_nil {α V} (guesses : GuessList α V) : guesses.rewriteWord [] = [] := by rfl

@[simp]
lemma rewriteWord_append {α V} (guesses : GuessList α V) (l₁ l₂ : List (Symbol α V)) :
    guesses.rewriteWord (l₁ ++ l₂) = guesses.rewriteWord l₁ ++ guesses.rewriteWord l₂ :=
  List.flatMap_append

@[simp]
lemma rewriteWord_cons {α V} (guesses : GuessList α V) (a : Symbol α V) (l : List (Symbol α V)) :
    guesses.rewriteWord (a::l) = guesses.rewriteSymbol a ++ guesses.rewriteWord l :=
  List.flatMap_cons

@[simp]
lemma empty_rewriteSymbol {α V} [Fintype V] (w : Symbol α V) :
    (State.empty (α := α) (V := V)).guesses.rewriteSymbol w = [w] := by
  unfold State.empty rewriteSymbol
  simp only
  split <;> rfl

@[simp]
lemma empty_rewriteWord {α V} [Fintype V] (w : List (Symbol α V)) :
    (State.empty (α := α) (V := V)).guesses.rewriteWord w = w := by
  induction w with
  | nil => rfl
  | cons x xs ih => simp [ih]

end GuessList

namespace State

def applyTableAtIndex {α V T} [Fintype V]
  (source : State α V) (E : EDT0LGrammar α V T) (t : T)
  (target : State α V) (i : Fin source.length) :
    List (Symbol α V) :=
  target.guesses.rewriteWord (E.table t (source.get i))

def applyTable {α V T} [Fintype V]
  (source : State α V) (E : EDT0LGrammar α V T) (t : T)
  (target : State α V) :
    List (Symbol α V) :=
  target.guesses.rewriteWord (source.toList.flatMap (E.table t))

end State

structure ReplacementIsOkay {α V T : Type*} [Fintype V] (E : EDT0LGrammar α V T)
  (source : State α V) (t : T) (target : State α V) :
    Prop where
  nonterminals_prop : filterNonterminals (source.applyTable E t target) = target.toList
  guesses_prop :
    ∀ v,
      (h : source.guesses v ≠ .unknown) →
        target.guesses.rewriteWord (E.table t v) = List.map .terminal ((source.guesses v).toList h)

variable {α V T} [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  (state : State α V) (state' : State α V) (t : T) in
instance : Decidable (ReplacementIsOkay E state t state') :=
  if h : _ ∧ _ then
    isTrue ⟨h.left, h.right⟩
  else
    isFalse (by
      intro contra
      rw [not_and_or] at h
      obtain h | h := h
      · exact h contra.nonterminals_prop
      · exact h contra.guesses_prop )

namespace State

@[simp]
def labelSententialWord {α V} [Fintype V] (state : State α V) (i j : ℕ) :
    (w : List (Symbol α V))
      → (h : filterNonterminals w = (state.toList.drop i).take j)
      → List (Symbol α (Nonterminal α V))
  | .terminal a::ws, h =>
    .terminal a :: state.labelSententialWord i j ws (by simpa using h)
  | .nonterminal n::ws, h =>
    .nonterminal (.regular state ⟨i, by
      simp only [filterNonterminals_cons] at h
      by_contra contra
      simp only [not_lt] at contra
      rw [← State.toList_length, ← List.drop_eq_nil_iff] at contra
      rw [contra] at h
      simp at h ⟩) ::
    state.labelSententialWord (i + 1) (j - 1) ws (by
      simp only [filterNonterminals_cons] at h
      match j with
      | 0 =>
        simp at h
      | j + 1 =>
        by_cases h' : i < state.toList.length
        · rw [List.drop_eq_getElem_cons h', List.take_cons (Nat.zero_lt_succ j)] at h
          simp only [Nat.succ_eq_add_one, Nat.add_one_sub_one, List.cons.injEq] at h
          simp only [Nat.add_one_sub_one]
          exact h.right
        · simp only [not_lt, ← List.drop_eq_nil_iff] at h'
          rw [h'] at h
          simp at h )
  | [], _ => []

@[simp]
lemma labelSententialWord_nil {α V} [Fintype V] {state : State α V} {i j h} :
    state.labelSententialWord i j [] h = [] := rfl

lemma labelSententialWord_mem_iff {α V} [Fintype V] {state : State α V} {i j}
  {w : List (Symbol α V)} {h} {x : Symbol α (Nonterminal α V)} :
    x ∈ state.labelSententialWord i j w h ↔
    match x with
    | .terminal a => .terminal a ∈ w
    | .nonterminal n =>
      match n with
      | .regular q k => q = state ∧ k ≥ i ∧ k < i + j
      | _ => False := by
  cases x with
  | terminal a =>
    simp only
    fun_induction State.labelSententialWord
    · rename_i ih
      simp [ih]
    · rename_i ih
      simp [ih]
    · simp
  | nonterminal n =>
    simp only
    fun_induction State.labelSententialWord
    · rename_i i' j' a' ws' h' ih
      simp [ih]
    · rename_i i' j' n' ws' h' ih
      have hj : j' > 0 := by
        clear * - h'
        by_contra contra
        simp only [gt_iff_lt, not_lt, Nat.le_zero_eq] at contra
        subst contra
        simp at h'
      simp only [List.mem_cons, Symbol.nonterminal.injEq, ih, ge_iff_le]
      constructor
      · intro h
        obtain rfl | h := h
        · simp only [Std.le_refl, Nat.lt_add_right_iff_pos, true_and]
          by_contra contra
          simp only [not_lt, Nat.le_zero_eq] at contra
          subst contra
          simp at h'
        · split at h
          · obtain ⟨h1, h2, h3⟩ := h
            use h1
            use (Nat.le_of_succ_le h2)
            calc
              _ < _ := h3
              _ ≤ _ := by
                clear * - hj
                omega
          · exact h
      · intro h
        split at h
        · rename_i n q k
          obtain ⟨rfl, h1, h2⟩ := h
          simp only [Nonterminal.regular.injEq, heq_eq_eq, true_and]
          clear * - hj h1 h2
          grind only
        · simp only at h
    · rename_i i' j' h'
      simp only [filterNonterminals_nil, List.nil_eq, List.take_eq_nil_iff,
        List.drop_eq_nil_iff] at h'
      simp only [List.not_mem_nil, ge_iff_le, false_iff]
      intro contra
      obtain rfl | h' := h'
      · split at contra
        · obtain ⟨_, h1, h2⟩ := contra
          clear * - h1 h2
          omega
        · exact contra
      · split at contra
        · rename_i q k
          obtain ⟨rfl, contra, _⟩ := contra
          clear * - contra h'
          rw [State.toList_length] at h'
          have hk := k.prop
          omega
        · exact contra

@[simp]
lemma labelSententialWord_unlabel {α V} [Fintype V] {state : State α V} {i j}
  {w : List (Symbol α V)} {h} :
    (unlabelSententialWord <| state.labelSententialWord i j w h) = w := by
  fun_induction State.labelSententialWord
  · rename_i i' j' a' ws' h' ih
    simp [ih]
  · rename_i i' j' n' ws' h' ih
    simp only [unlabelSententialWord_cons_nonterminal, ih, List.cons.injEq,
      Symbol.nonterminal.injEq, and_true]
    clear ih
    simp only [filterNonterminals_cons] at h'
    --
    cases j'
    case zero => simp at h'
    case succ j' =>
    --
    rw [List.drop_eq_getElem_cons (i := i') (h := by
      by_contra contra
      simp only [not_lt] at contra
      rw [List.drop_eq_nil_of_le contra] at h'
      simp at h')] at h'
    rw [List.take_cons (i := _ + 1) (h := Nat.zero_lt_succ _)] at h'
    --
    simp only [Nat.add_one_sub_one, List.cons.injEq] at h'
    --
    replace h' := h'.left
    simp only [h']
    unfold State.toList
    simp
  · rfl

def applyTableAtRange {α V T} [Fintype V] (source : State α V) (i j : ℕ)
  (_hij : i + j ≤ source.length)
  (E : EDT0LGrammar α V T) (t : T)
  (target : State α V) :
    List (Symbol α V) :=
  List.flatMap
    (source.applyTableAtIndex E t target)
    (List.take j (List.drop i (List.finRange source.length)))

@[simp]
lemma applyTableAtRange_length_zero {α V T} [Fintype V] (source : State α V) (i : ℕ) {h}
  (E : EDT0LGrammar α V T) (t : T)
  (target : State α V) :
    source.applyTableAtRange i 0 h E t target = [] := rfl

@[simp]
lemma applyTableAtRange_length_one {α V T} [Fintype V] (source : State α V) (i : ℕ) {h}
  (E : EDT0LGrammar α V T) (t : T)
  (target : State α V) :
    source.applyTableAtRange i 1 h E t target =
    source.applyTableAtIndex E t target ⟨i, by omega⟩ := by
  unfold applyTableAtRange
  have : i < source.length := Nat.lt_of_lt_of_eq h rfl
  have : i < List.length (List.finRange source.length) := by simp_all
  rw [List.take_one]
  simp [*]

@[simp]
lemma applyTableAtRange_all {α V T} [Fintype V] (source : State α V)
  (E : EDT0LGrammar α V T) (t : T)
  (target : State α V) :
    source.applyTableAtRange 0 source.length (by simp) E t target =
    source.applyTable E t target := by
  unfold applyTableAtRange applyTable applyTableAtIndex
  simp only [List.drop_zero]
  conv => lhs; rhs; arg 1; rw [← List.length_finRange (n := source.length)]
  simp only [List.take_length]
  unfold GuessList.rewriteWord State.toList
  rw [← List.flatMap_map, ← List.flatMap_assoc]
  refine congrArg (List.flatMap target.guesses.rewriteSymbol) ?_
  rw [List.flatMap_map, ← List.flatMap_map (g := E.table t)]
  refine congrArg (List.flatMap (E.table t)) ?_
  exact Eq.symm List.ofFn_eq_map

lemma applyTableAtRange_add_one {α V T} [Fintype V] (source : State α V) (i j : ℕ)
  (hikj : i + (j + 1) ≤ source.length)
  (E : EDT0LGrammar α V T) (t : T)
  (target : State α V) :
    source.applyTableAtRange i (j + 1) hikj E t target
    = source.applyTableAtRange i j (by omega) E t target
      ++ source.applyTableAtRange (i + j) 1 (by omega) E t target := by
  unfold applyTableAtRange
  rw [List.take_add_one]
  have : i + j < source.length := Nat.lt_of_lt_of_eq hikj rfl
  simp only [List.getElem?_drop, List.length_finRange, getElem?_pos, List.getElem_finRange,
    Fin.cast_mk, Option.toList_some, List.flatMap_append, List.flatMap_cons, List.flatMap_nil,
    List.append_nil, List.append_cancel_left_eq, this]
  rw [List.take_one]
  simp [*]

lemma applyTableAtRange_append {α V T} [Fintype V] (source : State α V) (i j k : ℕ)
  (hikj : i + (j + k) ≤ source.length)
  (E : EDT0LGrammar α V T) (t : T)
  (target : State α V) :
    source.applyTableAtRange i (j + k) hikj E t target
    = source.applyTableAtRange i j (by omega) E t target
      ++ source.applyTableAtRange (i + j) k (by omega) E t target := by
  induction k with
  | zero =>
    simp only [add_zero, applyTableAtRange_length_zero, List.append_nil]
  | succ k ih =>
    simp only [← Nat.add_assoc,
      applyTableAtRange_add_one (j := j + k),
      applyTableAtRange_add_one (j := k)]
    rw [ih, List.append_assoc]

end State

namespace ReplacementIsOkay

theorem applyTableAtIndex_prop {α V T} [Fintype V] (E : EDT0LGrammar α V T)
  (state : State α V) (i : Fin state.length) (t : T) (state' : State α V)
  {h'}
  (h : ReplacementIsOkay E state t state') :
  filterNonterminals (state.applyTableAtIndex E t state' i) =
    List.take (filterNonterminals <| state.applyTableAtIndex E t state' i).length
      (List.drop
          (filterNonterminals <| state.applyTableAtRange 0 ↑i h' E t state').length
          state'.toList) := by
  rw [← h.nonterminals_prop]
  clear h
  have := state.applyTableAtRange_append 0 i (state.length - i) (hikj := by omega) E t state'
  simp only [Fin.is_le', Nat.add_sub_cancel', State.applyTableAtRange_all, zero_add] at this
  rw [this]
  clear this
  simp only [filterNonterminals_append, List.drop_left']
  have h := state.applyTableAtRange_append i 1 (state.length - i - 1) (hikj := by omega) E t state'
  simp only [show 1 + (state.length - ↑i - 1) = state.length - i by omega] at h
  rw [h]
  clear h
  simp

end ReplacementIsOkay

def grammar {α V T : Type*} [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T) :
    EDT0LGrammar α (Nonterminal α V) (Table α V T) where
  initial := .init
  table :=
    fun t v ↦
      match v with
      | .init =>
        match t with
        | .init =>
          let q : State α V := {
            finLength := ⟨1, have := Nonempty.intro E.initial; Nat.AtLeastTwo.one_lt⟩
            get' := fun _ ↦ E.initial
            inj' := fun x y ↦ by grind only
            guesses := fun _ ↦ .unknown
            guesses_prop' := fun _ ↦ rfl
            }
          --
          [ .nonterminal <| .starter q,
            .nonterminal <| .regular q ⟨0, Nat.zero_lt_succ 0⟩ ]
        | .finish | .step _ _ =>
          [ .nonterminal .dead ]
      | .dead =>
        [ .nonterminal .dead ]
      | .starter state =>
        match t with
        | .init =>
          [ .nonterminal .dead ]
        | .finish =>
          if state = .empty then [] else [.nonterminal .dead]
        | .step t state' =>
          if h : ReplacementIsOkay E state t state' then
            [.nonterminal <| .starter state']
          else
            [.nonterminal .dead]
      | .regular state i =>
        match t with
        | .init | .finish => []
        | .step t state' =>
          if h : ReplacementIsOkay E state t state' then
            state'.labelSententialWord
              (List.length
                <| filterNonterminals
                <| state.applyTableAtRange 0 i (by simp_all) E t state')
              (List.length
                <| filterNonterminals
                <| state.applyTableAtIndex E t state' i)
              (state.applyTableAtIndex E t state' i)
              (ReplacementIsOkay.applyTableAtIndex_prop E state i t state' h)
          else
            []

inductive NormalForm.deadP {α V} [Fintype V] (w : List (Symbol α (Nonterminal α V))) : Prop where
  | intro (u : List α) (h : w = .nonterminal .dead :: u.map .terminal)

def NormalForm.initP {α V} [Fintype V] (w : List (Symbol α (Nonterminal α V))) : Prop :=
  w = [ .nonterminal .init ]

inductive NormalForm.acceptedP {α V T} [Fintype V] (E : EDT0LGrammar α V T)
  (w : List (Symbol α (Nonterminal α V)))
  (u : List α) :
    Prop where
  | intro
      (h : w = u.map .terminal)
      (h' : E.Generates (u.map .terminal))

inductive NormalForm.stepP {α V T} [Fintype V] (E : EDT0LGrammar α V T)
  (w : List (Symbol α (Nonterminal α V)))
  (state : State α V)
  (ww : List (Symbol α V)) :
    Prop where
  | intro
    (u : List (Symbol α (Nonterminal α V)))
    (h₀ : ∀ x, .nonterminal x ∈ u → match x with | .regular q _ => state = q | _ => False)
    (h₁ : w = (.nonterminal <| .starter state)::u)
    (h₂ : state.toList = filterNonterminals (unlabelSententialWord u))
    (hww : E.Generates ww)
    (h_u : unlabelSententialWord u = state.guesses.rewriteWord ww)

inductive NormalForm {α V T} [Fintype V] (E : EDT0LGrammar α V T)
  (w : List (Symbol α (Nonterminal α V))) :
    Prop where
  | dead (prop : NormalForm.deadP w)
  | init (prop : NormalForm.initP w)
  | accepted (u) (prop : NormalForm.acceptedP E w u)
  | step (state) (ww) (prop : NormalForm.stepP E w state ww)

lemma NormalForm.deadP_apply_table {α V T} [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  (w : List (Symbol α (Nonterminal α V)))
  (t : Table α V T)
  (h : deadP w) :
    deadP ((grammar E).rewriteWord t w) := by
  obtain ⟨u, rfl⟩ := h
  simp only [rewriteWord_cons, rewriteSymbol_nonterminal, rewriteWord_terminals]
  exact .intro _ rfl

lemma NormalForm.initP_apply_table {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V] [DecidableEq T]
  (E : EDT0LGrammar α V T)
  (w : List (Symbol α (Nonterminal α V)))
  (t : Table α V T)
  (h : initP w) :
    if t = .init then
      stepP E ((grammar E).rewriteWord t w)
        {
          finLength := ⟨1, have := Nonempty.intro E.initial; Nat.AtLeastTwo.one_lt⟩
          get' := fun _ ↦ E.initial
          inj' := fun x y ↦ by grind only
          guesses := fun _ ↦ .unknown
          guesses_prop' := fun _ ↦ rfl
        }
        E.initialWord
    else
      deadP ((grammar E).rewriteWord t w) := by
  cases t with
  | init =>
    simp only [↓reduceIte]
    let q : State α V := {
      finLength := ⟨1, have := Nonempty.intro E.initial; Nat.AtLeastTwo.one_lt⟩
      get' := fun _ ↦ E.initial
      inj' := fun x y ↦ by grind only
      guesses := fun _ ↦ .unknown
      guesses_prop' := fun _ ↦ rfl
      }
    obtain rfl := h
    exact .intro
      [.nonterminal <| .regular q ⟨0, Nat.zero_lt_succ 0⟩]
      (by
        intro x a
        simp_all only [List.mem_cons, Symbol.nonterminal.injEq, List.not_mem_nil, or_false, q])
      rfl
      rfl
      (generates_initial E)
      rfl
  | finish | step =>
    simp only [reduceCtorEq, ↓reduceIte]
    obtain rfl := h
    exact .intro [] rfl

lemma NormalForm.acceptedP_apply_table {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  (w : List (Symbol α (Nonterminal α V)))
  (t : Table α V T) {u}
  (h : acceptedP E w u) :
    (grammar E).rewriteWord t w = w := by
  obtain ⟨rfl⟩ := h
  simp

lemma NormalForm.stepP_apply_init {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  (w : List (Symbol α (Nonterminal α V)))
  {q ww}
  (h : stepP E w q ww) :
    deadP ((grammar E).rewriteWord .init w) := by
  obtain ⟨u, h0, rfl, h, hww, h_u⟩ := h
  let u' : List α := u.filterMap (fun x ↦ match x with | .terminal a => some a | _ => none)
  refine deadP.intro u' ?_
  simp only [rewriteWord_cons, rewriteSymbol_nonterminal]
  conv => lhs ; lhs ; change [.nonterminal .dead]
  simp only [List.cons_append, List.nil_append, List.cons.injEq, true_and]
  unfold u'
  clear * - h0
  induction u with
  | nil =>
    rfl
  | cons x xs ih =>
    replace ih := ih (fun x' hx ↦ h0 x' (List.mem_cons_of_mem x hx))
    simp only [rewriteWord_cons]
    cases x with
    | terminal _ =>
      simp [ih]
    | nonterminal n =>
      simp only [rewriteSymbol_nonterminal, ih, List.filterMap_cons_none, List.append_left_eq_self]
      cases n with
      | regular => rfl
      | init | starter | dead =>
        replace h0 := h0 _ List.mem_cons_self
        simp only at h0

lemma NormalForm.stepP_apply_finish {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  (w : List (Symbol α (Nonterminal α V)))
  {q ww}
  (h : stepP E w q ww)
  (u h₀ h₁ h₂ hww h_u)
  (h_choice : h = .intro (E := E) (w := w) u h₀ h₁ h₂ hww h_u) :
    if q = State.empty then
      acceptedP E ((grammar E).rewriteWord .finish w)
        (u.filterMap (fun x ↦ match x with | .terminal a => some a | _ => none))
    else
      deadP ((grammar E).rewriteWord .finish w) := by
  split
  · rename_i hq
    subst h₁
    let u' : List α := u.filterMap (fun x ↦ match x with | .terminal a => some a | _ => none)
    refine acceptedP.intro ?_ ?_
    · clear * - hq u h₀ u'
      -- subst u'
      simp only [rewriteWord_cons, rewriteSymbol_nonterminal]
      conv => lhs; lhs; tactic => simp only [grammar, dite_eq_ite, hq, ↓reduceIte, List.nil_eq]
      simp only [List.nil_append]
      --
      induction u with
      | nil =>
        rfl
      | cons x xs ih =>
        replace ih := ih (h₀ := fun x' h' ↦ h₀ x' (List.mem_cons_of_mem x h'))
        simp only [rewriteWord_cons]
        cases x with
        | terminal _ =>
          simp [ih]
        | nonterminal n =>
          cases n with
          | regular =>
            conv => lhs; lhs; simp only [grammar, dite_eq_ite, rewriteSymbol_nonterminal,
              List.nil_eq]
            simp only [List.nil_append, List.filterMap_cons_none]
            exact ih
          | init | dead | starter =>
            have h0 := h₀ _ (List.mem_cons_self)
            simp only at h0
    · have : ww = List.map .terminal u' := by
        subst u' hq
        have hh : ∀ x ∈ u, match x with | .terminal _ => True | .nonterminal _ => False := by
          intro x hx
          split
          · trivial
          · replace h₀ := h₀ _ hx
            split at h₀
            · rename_i i
              subst h₀
              have i' : Fin 0 := i
              clear * - i'
              have : IsEmpty (Fin 0) := Fin.isEmpty'
              exact IsEmpty.false i'
            · exact h₀
        simp only [GuessList.empty_rewriteWord] at h_u
        subst h_u
        clear * - hh
        induction u with
        | nil =>
          rfl
        | cons x xs ih =>
          replace ih := ih (fun x' h' ↦ hh x' (List.mem_cons_of_mem x h'))
          replace hh := hh x List.mem_cons_self
          split at hh
          · simp only [unlabelSententialWord_cons_terminal, Option.some.injEq,
              List.filterMap_cons_some, List.map_cons, List.cons.injEq, true_and]
            exact ih
          · simp only at hh
      rw [this] at hww
      exact hww
  · rename_i hq
    clear * - hq u h₁ h₀
    subst h₁
    let u' : List α := u.filterMap (fun x ↦ match x with | .terminal a => some a | _ => none)
    refine deadP.intro u' ?_
    subst u'
    induction u with
    | nil =>
      simp [grammar, hq]
    | cons x xs ih =>
      replace ih := ih (h₀ := fun x' h' ↦ h₀ x' (List.mem_cons_of_mem x h'))
      simp only [rewriteWord_cons, rewriteSymbol_nonterminal]
      conv => lhs; lhs; tactic => simp only [grammar, dite_eq_ite, hq, ↓reduceIte]
      simp only [List.cons_append, List.nil_append, List.cons.injEq, true_and]
      simp only [rewriteWord_cons, rewriteSymbol_nonterminal] at ih
      conv at ih => lhs; lhs; tactic => simp only [grammar, dite_eq_ite, hq, ↓reduceIte]
      simp only [List.cons_append, List.nil_append, List.cons.injEq, true_and] at ih
      rw [ih]
      cases x with
      | terminal _ =>
        simp
      | nonterminal n =>
        have h0 := h₀ n List.mem_cons_self
        cases n with
        | regular =>
          simp [grammar]
        | init | dead | starter =>
          simp at h0

private def NormalForm.stepP_apply_step.rewriteNonterminalSymbol {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  {state t target}
  (h' : ReplacementIsOkay E state t target)
  (n : Nonterminal α V)
  (h₀ : match n with | .regular q _ => state = q | _ => False) :
    List (Symbol α (Nonterminal α V)) :=
  match hn : n with
  | .regular q' i =>
    if hq : q' = state then
      target.labelSententialWord
        (List.length
          <| filterNonterminals
          <| state.applyTableAtRange 0 i (by subst hq; simp_all) E t target)
        (List.length
          <| filterNonterminals
          <| state.applyTableAtIndex E t target ⟨i, by subst hq; omega⟩)
        (state.applyTableAtIndex E t target ⟨i, by subst hq; omega⟩)
        (ReplacementIsOkay.applyTableAtIndex_prop E state ⟨i, by subst hq; omega⟩ t target h')
    else
      nomatch show False by simp_all
  | .init | .dead | .starter _ =>
    nomatch show False by simp at h₀

private def NormalForm.stepP_apply_step.rewriteWord {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  {state t target}
  (h' : ReplacementIsOkay E state t target)
  (u : List (Symbol α (Nonterminal α V)))
  (h₀ : ∀ x, .nonterminal x ∈ u → match x with | .regular q _ => state = q | _ => False) :
    List (Symbol α (Nonterminal α V)) :=
      u.attach.flatMap fun x ↦
        match hx : x.val with
        | .terminal a => [.terminal a]
        | .nonterminal n =>
          rewriteNonterminalSymbol E h' n (h₀ _ (by grind))

@[simp]
private lemma NormalForm.stepP_apply_step.rewriteWord_nil {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  {state t target}
  (h' : ReplacementIsOkay E state t target) :
    rewriteWord E h' [] (by simp) = [] := rfl

@[simp]
private lemma NormalForm.stepP_apply_step.rewriteWord_cons_nonterminal {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  {state t target}
  (h' : ReplacementIsOkay E state t target)
  (u : Nonterminal α V)
  (us : List (Symbol α (Nonterminal α V)))
  (h₀ : ∀ x, .nonterminal x ∈ .nonterminal u::us →
            match x with | .regular q _ => state = q | _ => False) :
    stepP_apply_step.rewriteWord E h' (.nonterminal u::us) h₀ =
    stepP_apply_step.rewriteNonterminalSymbol E h' u (h₀ u List.mem_cons_self)
    ++ stepP_apply_step.rewriteWord E h' us (fun x' hx' ↦ h₀ x' (List.mem_cons_of_mem _ hx')) := by
  unfold rewriteWord
  simp only [List.attach_cons, List.flatMap_cons, List.append_cancel_left_eq]
  rw [List.flatMap_map]

@[simp]
private lemma NormalForm.stepP_apply_step.rewriteWord_cons_terminal {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  {state t target}
  (h' : ReplacementIsOkay E state t target)
  (u : α)
  (us : List (Symbol α (Nonterminal α V)))
  (h₀ : ∀ x, .nonterminal x ∈ .terminal u::us →
            match x with | .regular q _ => state = q | _ => False) :
    stepP_apply_step.rewriteWord E h' (.terminal u::us) h₀ =
      .terminal u ::
       stepP_apply_step.rewriteWord E h' us (fun x' hx' ↦ h₀ x' (List.mem_cons_of_mem _ hx')) := by
  unfold rewriteWord
  simp only [List.attach_cons, List.flatMap_cons, List.cons_append, List.nil_append,
    List.cons.injEq, true_and]
  rw [List.flatMap_map]

private lemma NormalForm.stepP_apply_step.rewriteNonterminalSymbol_nonterminal_mem {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  {state t target}
  (h' : ReplacementIsOkay E state t target)
  (n : Nonterminal α V)
  (h₀ : match n with | .regular q _ => state = q | _ => False)
  (x : Nonterminal α V) :
    .nonterminal x ∈ stepP_apply_step.rewriteNonterminalSymbol E h' n h₀ →
    match x with
    | .regular q _ => q = target
    | _ => False := by
  split at h₀
  · simp only at h₀
    subst h₀
    unfold rewriteNonterminalSymbol
    simp only [↓reduceDIte, Fin.eta]
    intro y
    simp only [State.labelSententialWord_mem_iff] at y
    split at y
    · replace y := y.left
      simp [y]
    · simp only at y
  · simp only at h₀

private lemma NormalForm.stepP_apply_step.rewriteWord_nonterminal_mem {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  {state t target}
  (h' : ReplacementIsOkay E state t target)
  (u : List (Symbol α (Nonterminal α V)))
  (h₀ : ∀ x, .nonterminal x ∈ u → match x with | .regular q _ => state = q | _ => False)
  (x : Nonterminal α V) :
    .nonterminal x ∈ stepP_apply_step.rewriteWord E h' u h₀ →
    match x with
    | .regular q _ => q = target
    | _ => False := by
  intro h
  induction u with
  | nil =>
    simp at h
  | cons y ys ih =>
    replace ih := ih (fun x' hx' ↦ h₀ x' (List.mem_cons_of_mem y hx'))
    cases y with
    | terminal _ =>
      simp only [rewriteWord_cons_terminal, List.mem_cons, reduceCtorEq, false_or] at h
      exact ih h
    | nonterminal _ =>
      simp only [rewriteWord_cons_nonterminal, List.mem_append] at h
      obtain h | h := h
      · rename_i n'
        have := stepP_apply_step.rewriteNonterminalSymbol_nonterminal_mem E h' n'
          (h₀ n' (List.mem_cons_self))
        exact NormalForm.stepP_apply_step.rewriteNonterminalSymbol_nonterminal_mem
              E h' n' (h₀ n' List.mem_cons_self) x h
      · exact ih h

private lemma NormalForm.stepP_apply_step.grammar_rewriteWord_eq {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  {state t target}
  (h' : ReplacementIsOkay E state t target)
  (u : List (Symbol α (Nonterminal α V)))
  (h₀ : ∀ x, .nonterminal x ∈ u → match x with | .regular q _ => state = q | _ => False) :
    (grammar E).rewriteWord (Table.step t target) u = stepP_apply_step.rewriteWord E h' u h₀ := by
  induction u with
  | nil =>
    rfl
  | cons x xs ih =>
    replace ih := ih (fun x' hx' ↦ h₀ x' (List.mem_cons_of_mem x hx'))
    cases x with
    | terminal a =>
      simp [ih]
    | nonterminal n =>
      simp only [rewriteWord_cons, rewriteSymbol_nonterminal, ih, rewriteWord_cons_nonterminal,
        List.append_cancel_right_eq]
      unfold rewriteNonterminalSymbol grammar
      simp only [dite_eq_ite, ne_eq]
      split
      · simp only
        split
      · simp only
        split
      · rename_i v' state'
        replace h₀ := h₀ (.starter state') List.mem_cons_self
        split at h₀
        · subst h₀
          rename_i heq
          simp_all
        · simp at h₀
      · rename_i v' state' i'
        replace h₀ := h₀ _ List.mem_cons_self
        simp only at h₀
        subst h₀
        simp_all

private lemma NormalForm.stepP_apply_step.target_toList_eq {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  {state t target}
  (h' : ReplacementIsOkay E state t target)
  (u : List (Symbol α (Nonterminal α V)))
  (h₀ : ∀ x, .nonterminal x ∈ u → match x with | .regular q _ => state = q | _ => False)
  (h₂ : state.toList = filterNonterminals (unlabelSententialWord u)) :
    target.toList =
    filterNonterminals (unlabelSententialWord (stepP_apply_step.rewriteWord E h' u h₀)) := by
  rw [← h'.nonterminals_prop]
  unfold State.applyTable
  rw [h₂]
  clear * -
  induction u with
  | nil =>
    rfl
  | cons x xs ih =>
    replace ih := ih (fun x' hx' ↦ h₀ x' (List.mem_cons_of_mem x hx'))
    cases x with
    | terminal a =>
      simp [ih]
    | nonterminal n =>
      cases n with
      | init | dead | starter => 
        have h0 := h₀ _ List.mem_cons_self
        simp only at h0
      | regular =>
        rename_i state' i'
        have h0 := h₀ _ List.mem_cons_self
        simp only at h0
        subst state'
        simp only [unlabelSententialWord_cons_nonterminal, filterNonterminals_cons,
          List.flatMap_cons, GuessList.rewriteWord_append, filterNonterminals_append, ih,
          rewriteWord_cons_nonterminal, unlabelSententialWord_append, List.append_cancel_right_eq]
        clear * -
        unfold rewriteNonterminalSymbol
        simp only [↓reduceDIte, Fin.eta]
        unfold State.applyTableAtIndex filterNonterminals
        refine congrArg (List.filterMap _) ?_
        have := h'.nonterminals_prop
        simp only [State.labelSententialWord_unlabel]

private lemma NormalForm.stepP_apply_step.unlabel_eq_target_guess {α V T} [Fintype V]
  [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  (t : T) (target : State α V) {q : State α V}
  {u : List (Symbol α (Nonterminal α V))}
  {h₀ :
    ∀ (x : Nonterminal α V),
      Symbol.nonterminal x ∈ u →
        match x with
        | Nonterminal.regular q_1 _ => q = q_1
        | _ => False}
  {ww : List (Symbol α V)}
  (h_u : unlabelSententialWord u = q.guesses.rewriteWord ww)
  (h' : ReplacementIsOkay E q t target) :
    unlabelSententialWord (stepP_apply_step.rewriteWord E h' u h₀) =
      target.guesses.rewriteWord (E.rewriteWord t ww) := by
  have h := h'.guesses_prop
  --
  let rec go:
      (ww : List (Symbol α V)) →
      (u : List (Symbol α (Nonterminal α V))) → (h₀ : _) →
      (h_u : unlabelSententialWord u = q.guesses.rewriteWord ww) →
        unlabelSententialWord (rewriteWord E h' u h₀) =
        target.guesses.rewriteWord (E.rewriteWord t ww)
    | [], [], _, _ => rfl
    | [], a::as, h1, h2 => by
      exfalso
      cases a with
      | terminal _ => simp at h2
      | nonterminal n =>
        replace h1 := h1 n List.mem_cons_self
        cases n with
        | regular =>
          simp at h2
        | init | dead | starter =>
          simp at h1
    | a::as, [], h1, h2 => by
      simp only [unlabelSententialWord_nil, GuessList.rewriteWord_cons, List.nil_eq,
        List.append_eq_nil_iff] at h2
      obtain ⟨h2, h2r⟩ := h2
      cases a with
      | terminal =>
        simp at h2
      | nonterminal v =>
        by_cases h_v : q.guesses v = .unknown
        · simp [GuessList.rewriteSymbol, h_v] at h2
        · have h1 := h v h_v
          simp only [rewriteWord_nil, unlabelSententialWord_nil, rewriteWord_cons,
            rewriteSymbol_nonterminal, GuessList.rewriteWord_append, List.nil_eq,
            List.append_eq_nil_iff]
          --
          have R := go as [] (fun x hx ↦ by simp at hx) (by
            simp only [unlabelSententialWord_nil, List.nil_eq]
            exact h2r )
          simp only [rewriteWord_nil, unlabelSententialWord_nil, List.nil_eq] at R
          rw [h1, R]
          simp only [List.map_eq_nil_iff, and_true]
          --
          simp [GuessList.rewriteSymbol] at h2
          split at h2
          · simp at h2
          · simp at h2
          · rename_i heq
            unfold Guess.toList
            split
            · split
            · rfl
            · rename_i heq1 _
              rw [heq] at heq1
              simp at heq1
    | x::xs, y::ys, h1, h2 => by
      cases y with
      | terminal a =>
        cases x with
        | terminal a' =>
          simp only [unlabelSententialWord_cons_terminal, GuessList.rewriteWord_cons,
            GuessList.rewriteSymbol_terminal, List.cons_append, List.nil_append, List.cons.injEq,
            Symbol.terminal.injEq] at h2
          obtain ⟨rfl, h2⟩ := h2
          simp only [rewriteWord_cons_terminal, unlabelSententialWord_cons_terminal,
            rewriteWord_cons, rewriteSymbol_terminal, List.cons_append, List.nil_append,
            GuessList.rewriteWord_cons, GuessList.rewriteSymbol_terminal, List.cons.injEq, true_and]
          --
          exact go xs ys (fun x hx ↦ h1 x (List.mem_cons_of_mem _ hx)) h2
        | nonterminal v' =>
          if hq : q.guesses v' = .unknown then
            simp [GuessList.rewriteSymbol, hq] at h2
          else
            replace h := h v' hq
            conv => rhs; simp only [rewriteWord_cons, rewriteSymbol_nonterminal, 
                          GuessList.rewriteWord_append]
            rw [h]
            unfold Guess.toList
            split
            · split
            · conv => rhs; simp only [List.map_nil, List.nil_append]
              conv at h2 =>
                rhs
                simp only [GuessList.rewriteWord_cons, GuessList.rewriteSymbol,
                  List.nil_append, *]
              --
              exact go xs (.terminal a::ys) h1 h2
            · simp only [rewriteWord_cons_terminal, unlabelSententialWord_cons_terminal,
              List.map_cons, List.map_nil, List.cons_append, List.nil_append, List.cons.injEq,
              Symbol.terminal.injEq]
              --
              simp only [unlabelSententialWord_cons_terminal, GuessList.rewriteWord_cons,
                GuessList.rewriteSymbol, List.cons_append, List.nil_append, List.cons.injEq,
                Symbol.terminal.injEq, *] at h2
              --
              use h2.left
              --
              exact go xs ys (fun x hx ↦ h1 x (List.mem_cons_of_mem _ hx)) h2.right
      | nonterminal v =>
        have h1' := h1 v List.mem_cons_self
        split at h1' <;> try simp only at h1'
        rename_i q' i'
        subst q'
        cases x with
        | terminal a' =>
          simp at h2
        | nonterminal v' =>
          conv at h2 => rhs ; simp only [GuessList.rewriteWord_cons, GuessList.rewriteSymbol]
          split at h2
          · simp only [unlabelSententialWord_cons_nonterminal, List.cons_append, List.nil_append,
              List.cons.injEq, Symbol.nonterminal.injEq] at h2
            simp only [rewriteWord_cons_nonterminal, unlabelSententialWord_append, rewriteWord_cons,
              rewriteSymbol_nonterminal, GuessList.rewriteWord_append]
            obtain ⟨rfl, h2⟩ := h2
            rename_i heq
            simp only [rewriteNonterminalSymbol, ↓reduceDIte, State.applyTableAtIndex, Fin.eta,
              State.labelSententialWord_unlabel, List.append_cancel_left_eq]
            exact go xs ys (fun x hx ↦ h1 x (List.mem_cons_of_mem _ hx)) h2
          · simp at h2
          · simp only [List.nil_append] at h2
            conv =>
              rhs
              simp only [rewriteWord_cons, rewriteSymbol_nonterminal,
                GuessList.rewriteWord_append, ne_eq, reduceCtorEq, not_false_eq_true, *]
              change [] ++ _
              simp only [List.nil_append]
            exact go _ _ h1 h2
  --
  exact go ww u h₀ h_u

lemma NormalForm.stepP_apply_step {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  (w : List (Symbol α (Nonterminal α V)))
  {q ww}
  (h : stepP E w q ww)
  (t : T)
  (target : State α V)
  (u h₀ h₁ h₂ hww h_u)
  (h_choice : h = .intro (E := E) (w := w) u h₀ h₁ h₂ hww h_u) :
    if ReplacementIsOkay E q t target then
      stepP E ((grammar E).rewriteWord (.step t target) w) target (E.rewriteWord t ww)
    else
      deadP ((grammar E).rewriteWord (.step t target) w) := by
  split
  · rename_i h'
    subst h_choice
    refine stepP.intro
      (stepP_apply_step.rewriteWord E h' u h₀)
      ?_ ?_ ?_ ?_ ?_
    · intro x hx
      have := stepP_apply_step.rewriteWord_nonterminal_mem E h' u h₀ _ hx
      clear * - this
      split <;> simp_all
    · subst h₁
      simp only [rewriteWord_cons, rewriteSymbol_nonterminal]
      conv => lhs; lhs; simp only [grammar, dite_eq_ite, h', ↓reduceIte]
      simp only [List.cons_append, List.nil_append, List.cons.injEq, true_and]
      exact stepP_apply_step.grammar_rewriteWord_eq E h' u h₀
    · exact stepP_apply_step.target_toList_eq E h' u h₀ h₂
    · exact generates_rewriteWord_tail hww t
    · exact NormalForm.stepP_apply_step.unlabel_eq_target_guess E t target h_u h'
  · let u' : List α := u.filterMap (fun x ↦ match x with | .terminal a => some a | _ => none)
    refine deadP.intro u' ?_
    subst u'
    rename_i h'
    subst h₁
    clear * - h' h₀
    induction u with
    | nil =>
      simp [h', grammar]
    | cons a as ih =>
      simp only [rewriteWord_cons, rewriteSymbol_nonterminal]
      --
      replace ih := ih (h₀ := fun x hx ↦ h₀ x (List.mem_cons_of_mem a hx))
      simp only [rewriteWord_cons, rewriteSymbol_nonterminal] at ih
      conv at ih => lhs; lhs; simp only [grammar, dite_eq_ite, h', ↓reduceIte]
      simp only [List.cons_append, List.nil_append, List.cons.injEq, true_and] at ih
      --
      cases a with
      | terminal a =>
        rw [ih]
        conv => lhs; lhs; simp only [grammar, dite_eq_ite, h', ↓reduceIte]
        simp
      | nonterminal v =>
        rw [ih]
        conv => lhs; lhs; simp only [grammar, dite_eq_ite, h', ↓reduceIte]
        simp only [rewriteSymbol_nonterminal, List.cons_append, List.nil_append,
          List.filterMap_cons_none, List.cons.injEq, List.append_left_eq_self, true_and]
        --
        replace h₀ := h₀ v List.mem_cons_self
        split at h₀
        · subst h₀
          simp [grammar, h']
        · simp only at h₀

lemma NormalForm.generated {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  (w : List (Symbol α (Nonterminal α V)))
  (h : (grammar E).Generates w) :
    NormalForm E w := by
  classical
  induction h with
  | refl =>
    exact .init rfl
  | tail hy hyz ih =>
    rename_i x y z
    obtain ⟨t, rfl⟩ := hyz
    cases ih with
    | dead prop =>
      exact .dead (deadP_apply_table E y t prop)
    | init prop =>
      have := initP_apply_table E y t prop
      split at this
      · exact step _ E.initialWord this
      · exact dead this
    | accepted u prop =>
      rw [acceptedP_apply_table E y t prop]
      exact accepted _ prop
    | step q ww prop =>
      cases hp : prop with
      | intro u h₀ h₁ h₂ hww h_u =>
      --
      cases t with
      | init =>
        exact dead (stepP_apply_init E y prop)
      | finish =>
        have := stepP_apply_finish E y prop u h₀ h₁ h₂ hww h_u hp
        split at this
        · exact accepted _ this
        · exact dead this
      | step t target =>
        have := stepP_apply_step E y prop t target u h₀ h₁ h₂ hww h_u hp
        split at this
        · exact step _ _ this
        · exact dead this

lemma grammar_language_imp {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  (w : List α)
  (h : w ∈ (grammar E).language) :
    w ∈ E.language := by
  unfold EDT0LGrammar.language at h
  change (grammar E).Generates (List.map Symbol.terminal w) at h
  replace h := NormalForm.generated _ _ h
  cases h with
  | dead prop =>
    exfalso
    obtain ⟨u, h⟩ := prop
    have : .nonterminal .dead ∈ List.map (Symbol.terminal (N := Nonterminal α V)) w := by
      rw [h]
      exact List.mem_cons_self
    simp at this
  | init prop =>
    exfalso
    unfold NormalForm.initP at prop
    have : .nonterminal .init ∈ List.map (Symbol.terminal (N := Nonterminal α V)) w := by
      rw [prop]
      exact List.mem_cons_self
    simp at this
  | accepted u prop =>
    have ⟨huw, h⟩ := prop
    unfold EDT0LGrammar.language
    change E.Generates (List.map Symbol.terminal w)
    have : w = u := by
      clear * - huw
      induction u generalizing w with
      | nil =>
        simpa using huw
      | cons a as ih =>
        cases w with
        | nil =>
          simp at huw
        | cons b bs =>
          simp only [List.map_cons, List.cons.injEq, Symbol.terminal.injEq] at huw
          obtain ⟨rfl, huw⟩ := huw
          rw [ih bs huw]
    rw [this]
    exact h
  | step state ww prop =>
    exfalso
    obtain ⟨u,_,h,_⟩ := prop
    have : .nonterminal (.starter state) ∈ List.map (Symbol.terminal (N := Nonterminal α V)) w := by
      rw [h]
      exact List.mem_cons_self
    simp at this

protected def grammar.state.guesses {α V T} (E : EDT0LGrammar α V T) (s : List T) (i : ℕ) :
    GuessList α V :=
  fun v ↦
  match E.rewriteSeq (s.drop (i + 1)) [.nonterminal v] with
  | [] => .empty
  | [.terminal a] => .single a
  | [.nonterminal _] | _::_::_ => .unknown

@[simp]
protected lemma grammar.state.guesses_final {α V T} [Fintype V]
  (E : EDT0LGrammar α V T)
  (s : List T)
  (h : s.length > 0) :
    grammar.state.guesses E s (s.length - 1) = State.empty.guesses := by
  unfold State.empty state.guesses
  have : s.length - 1 + 1 = s.length := Nat.sub_add_cancel h
  simp [this]

protected def grammar.state.sentential {α V T} (E : EDT0LGrammar α V T) (s : List T) (i : ℕ) :
    List (Symbol α V) := E.rewriteSeq (s.take (i + 1)) E.initialWord

protected def grammar.state.unknownNonterminals {α V T} [DecidableEq α] (E : EDT0LGrammar α V T)
  (s : List T) (i : ℕ) :
    List V :=
  (filterNonterminals (grammar.state.sentential E s i)).filter
    fun v ↦ grammar.state.guesses E s i v == .unknown

protected lemma grammar.state.unknownNonterminals_nodup {α V T} [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  (w : List α)
  (s : List T)
  (s_derives_w : E.rewriteSeq s E.initialWord = w.map .terminal)
  (is_lult :
    ∀ (v : V) (i : ℕ),
      i ≤ s.length →
        (filterNonterminals (E.rewriteSeq (s.take i) E.initialWord)).count v ≤ 1 ∨
        List.length (E.rewriteSeq (s.drop i) [.nonterminal v]) ≤ 1)
  (i : ℕ)
  (hi : i < s.length) :
    (grammar.state.unknownNonterminals E s i).Nodup := by
  rw [List.nodup_iff_count_le_one]
  intro v
  unfold grammar.state.unknownNonterminals
  by_cases hh : state.guesses E s i v == Guess.unknown
  · simp only [hh, List.count_filter]
    have is_lult1 := is_lult v (i + 1) (Nat.succ_le_of_lt hi)
    clear is_lult
    --
    by_contra contra
    unfold state.sentential at contra
    simp only [ge_iff_le, not_le] at contra
    -- simp only [filterNonterminals_count_eq, ge_iff_le, not_le] at contra
    --
    obtain is_lult1 | is_lult1 := is_lult1
    · clear * - is_lult1 contra
      omega
    · unfold state.guesses at hh
      split at hh
      · clear * - hh; trivial
      · clear * - hh; trivial
      · rename_i nn heq
        rw [← List.take_append_drop (i + 1) s, rewriteSeq_seq_append] at s_derives_w
        --
        have : .nonterminal v ∈ E.rewriteSeq (List.take (i + 1) s) E.initialWord := by
          clear * - contra
          simp only [filterNonterminals_count] at contra
          grind
        rw [List.mem_iff_append] at this
        obtain ⟨x,y,hh⟩ := this
        --
        rw [hh] at s_derives_w
        simp only [rewriteSeq_append] at s_derives_w
        rw [rewriteSeq_cons, heq] at s_derives_w
        have : (.nonterminal nn : Symbol α V) ∈ List.map .terminal w := by
          rw [← s_derives_w]
          simp
        simp at this
      · rename_i heq
        simp [heq] at is_lult1
  · grind

protected lemma grammar.state.unknownNonterminals_length_lt {α V T} [Fintype V]
  [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  (w : List α)
  (s : List T)
  (s_derives_w : E.rewriteSeq s E.initialWord = w.map .terminal)
  (is_lult :
    ∀ (v : V) (i : ℕ),
      i ≤ s.length →
        (filterNonterminals (E.rewriteSeq (s.take i) E.initialWord)).count v ≤ 1 ∨
        List.length (E.rewriteSeq (s.drop i) [.nonterminal v]) ≤ 1)
  (i : ℕ)
  (hi : i < s.length) :
    (grammar.state.unknownNonterminals E s i).length < Fintype.card V + 1 := by
  by_contra contra
  have nodup := grammar.state.unknownNonterminals_nodup E w s s_derives_w is_lult i hi
  rw [← List.toFinset_card_of_nodup nodup] at contra
  simp only [not_lt] at contra
  clear * - contra
  have : (grammar.state.unknownNonterminals E s i).toFinset.card ≤ Fintype.card V :=
    Finset.card_le_univ (grammar.state.unknownNonterminals E s i).toFinset
  omega

protected lemma grammar.state.unknownNonterminals_prop {α V T} [DecidableEq α]
  (E : EDT0LGrammar α V T)
  (s : List T)
  (i : ℕ) :
    ∀ j, state.guesses E s i ((grammar.state.unknownNonterminals E s i).get j) = Guess.unknown := by
  intro i'
  unfold state.guesses
  split
  · exfalso
    rename_i heq
    unfold grammar.state.unknownNonterminals at heq
    simp only [List.get_eq_getElem] at heq
    change let x' := _; E.rewriteSeq _ [.nonterminal x'] = _ at heq
    extract_lets x' at heq
    --
    have h1 : state.guesses E s i x' = .empty := by
      unfold state.guesses
      split <;> simp_all
    --
    have h2 : state.guesses E s i x' = .unknown := by
      unfold x'
      clear * -
      grind
    --
    rw [h1] at h2
    clear * - h2
    trivial
  · exfalso
    rename_i a heq
    unfold grammar.state.unknownNonterminals at heq
    simp only [List.get_eq_getElem] at heq
    change let x' := _; E.rewriteSeq _ [.nonterminal x'] = _ at heq
    extract_lets x' at heq
    --
    have h1 : state.guesses E s i x' = .single a := by
      unfold state.guesses
      split <;> simp_all
    --
    have h2 : state.guesses E s i x' = .unknown := by
      unfold x'
      clear * -
      grind
    --
    rw [h1] at h2
    clear * - h2
    trivial
  · rfl
  · rfl

protected def grammar.state {α V T} [Fintype V] [DecidableEq V] [DecidableEq α]
  (E : EDT0LGrammar α V T)
  (w : List α)
  (s : List T)
  (s_derives_w : E.rewriteSeq s E.initialWord = w.map .terminal)
  (is_lult :
    ∀ (v : V) (i : ℕ),
      i ≤ s.length →
        (filterNonterminals (E.rewriteSeq (s.take i) E.initialWord)).count v ≤ 1 ∨
        List.length (E.rewriteSeq (s.drop i) [.nonterminal v]) ≤ 1)
  (i : ℕ)
  (hi : i < s.length) :
    State α V := 
  { finLength := ⟨(grammar.state.unknownNonterminals E s i).length,
                    grammar.state.unknownNonterminals_length_lt E w s s_derives_w is_lult i hi ⟩
    get' := (grammar.state.unknownNonterminals E s i).get
    inj' := List.nodup_iff_injective_get.mp
                <| grammar.state.unknownNonterminals_nodup E w s s_derives_w is_lult i hi
    guesses := state.guesses E s i
    guesses_prop' := grammar.state.unknownNonterminals_prop E s i }

protected lemma grammar.state_final {α V T} [Fintype V] [DecidableEq V] [DecidableEq α]
  (E : EDT0LGrammar α V T)
  (w : List α)
  (s : List T)
  (s_derives_w : E.rewriteSeq s E.initialWord = w.map .terminal)
  (is_lult :
    ∀ (v : V) (i : ℕ),
      i ≤ s.length →
        (filterNonterminals (E.rewriteSeq (s.take i) E.initialWord)).count v ≤ 1 ∨
        List.length (E.rewriteSeq (s.drop i) [.nonterminal v]) ≤ 1)
  (h : s.length > 0) :
    grammar.state E w s s_derives_w is_lult (s.length - 1) (Nat.sub_one_lt_of_lt h) = .empty := by
  unfold grammar.state
  ext1
  · simp only
    unfold state.unknownNonterminals state.sentential
    have : s.length - 1 + 1 = s.length := Nat.sub_add_cancel h
    simp_all only [gt_iff_lt, state.guesses_final, List.take_length, filterNonterminals_terminals,
      List.filter_nil, List.length_nil, Fin.zero_eta]
    rfl
  · simp only
    unfold state.unknownNonterminals state.sentential
    have : s.length - 1 + 1 = s.length := Nat.sub_add_cancel h
    rw [this, List.take_length, s_derives_w, filterNonterminals_terminals]
    simp only [List.filter_nil, List.length_nil]
    unfold State.empty
    simp only [Fin.coe_ofNat_eq_mod, Nat.zero_mod, heq_eq_eq]
    ext x : 1
    simp only [List.get_eq_getElem, List.length_nil]
    split
  · simp only
    exact state.guesses_final E s h

@[simp]
protected lemma grammar.state_toList_eq {α V T} [Fintype V] [DecidableEq V] [DecidableEq α]
  (E : EDT0LGrammar α V T)
  (w : List α)
  (s : List T)
  (s_derives_w : E.rewriteSeq s E.initialWord = w.map .terminal)
  (is_lult :
    ∀ (v : V) (i : ℕ),
      i ≤ s.length →
        (filterNonterminals (E.rewriteSeq (s.take i) E.initialWord)).count v ≤ 1 ∨
        List.length (E.rewriteSeq (s.drop i) [.nonterminal v]) ≤ 1)
  (i : ℕ)
  (hi : i < s.length) :
    (grammar.state E w s s_derives_w is_lult i hi).toList =
    grammar.state.unknownNonterminals E s i := by
  unfold grammar.state State.toList State.get
  simp only [List.get_eq_getElem]
  exact List.ofFn_getElem

protected lemma grammar.state_guesses_eq {α V T} [Fintype V] [DecidableEq V] [DecidableEq α]
  (E : EDT0LGrammar α V T)
  (w : List α)
  (s : List T)
  (s_derives_w : E.rewriteSeq s E.initialWord = w.map .terminal)
  (is_lult :
    ∀ (v : V) (i : ℕ),
      i ≤ s.length →
        (filterNonterminals (E.rewriteSeq (s.take i) E.initialWord)).count v ≤ 1 ∨
        List.length (E.rewriteSeq (s.drop i) [.nonterminal v]) ≤ 1)
  (i : ℕ)
  (hi : i < s.length) :
    (grammar.state E w s s_derives_w is_lult i hi).guesses =
      grammar.state.guesses E s i := rfl

protected lemma grammar.state_guesses_prop {α V T}
  (E : EDT0LGrammar α V T)
  (s : List T)
  (i : ℕ)
  (hi : i + 1 < s.length)
  (v x : V)
  (h : .nonterminal x ∈ E.table s[i + 1] v)
  (h' : grammar.state.guesses E s i v ≠ .unknown) :
    grammar.state.guesses E s (i + 1) x ≠ .unknown := by
  intro contra
  unfold state.guesses at h' contra
  --
  rw [List.mem_iff_append] at h
  obtain ⟨s1, s2, h⟩ := h
  --
  have drop : s.drop (i + 1) = s[i + 1]::s.drop (i + 1 + 1) := List.drop_eq_getElem_cons hi
  split at h' <;> simp at h'
  · rename_i heq1
    rw [drop, rewriteSeq_seq_cons] at heq1
    simp only [rewriteWord_cons, rewriteSymbol_nonterminal, h, rewriteWord_nil, List.append_nil,
      rewriteSeq_append, List.append_eq_nil_iff] at heq1
    replace heq1 := heq1.right
    rw [rewriteSeq_cons] at heq1
    simp only [List.append_eq_nil_iff] at heq1
    replace heq1 := heq1.left
    --
    split at contra <;> simp at contra
    all_goals {
      rename_i heq2
      rw [heq1] at heq2
      simp at heq2
    }
  · rename_i a1 heq1
    rw [drop, rewriteSeq_seq_cons] at heq1
    simp only [rewriteWord_cons, rewriteSymbol_nonterminal, h, rewriteWord_nil, List.append_nil,
      rewriteSeq_append] at heq1
    rw [rewriteSeq_cons] at heq1
    split at contra <;> simp at contra
    · rename_i a2 heq2
      rw [heq2] at heq1
      --
      have : .terminal a2 ∈ [(.terminal a1 : Symbol α V)] := by
        rw [← heq1]
        simp
      simp only [List.mem_cons, Symbol.terminal.injEq, List.not_mem_nil, or_false] at this
      subst this
      --
      simp_all
    · rename_i a2 heq2
      rw [heq2] at heq1
      have : .nonterminal a2 ∈ [(.terminal a1 : Symbol α V)] := by
        rw [← heq1]
        simp
      simp at this
    · rename_i h1 h2 t heq2
      rw [heq2] at heq1
      have : List.length [(.terminal a1 : Symbol α V)] > 1 := by
        rw [← heq1]
        simp only [List.cons_append, List.length_append, List.length_cons, gt_iff_lt]
        omega
      simp at this

protected def grammar.table {α V T} [Fintype V] [DecidableEq V] [DecidableEq α]
  (E : EDT0LGrammar α V T)
  (w : List α)
  (s : List T)
  (s_derives_w : E.rewriteSeq s E.initialWord = w.map .terminal)
  (is_lult :
    ∀ (v : V) (i : ℕ),
      i ≤ s.length →
        (filterNonterminals (E.rewriteSeq (s.take i) E.initialWord)).count v ≤ 1 ∨
        List.length (E.rewriteSeq (s.drop i) [.nonterminal v]) ≤ 1)
  (i : ℕ)
  (hi : i < s.length) :
    Table α V T := .step s[i] (grammar.state E w s s_derives_w is_lult i hi)

set_option linter.unusedDecidableInType false in
protected lemma grammar.table_prop {α V T} [Fintype V] [DecidableEq V] [DecidableEq α]
  (E : EDT0LGrammar α V T)
  (w : List α)
  (s : List T)
  (s_derives_w : E.rewriteSeq s E.initialWord = w.map .terminal)
  (is_lult :
    ∀ (v : V) (i : ℕ),
      i ≤ s.length →
        (filterNonterminals (E.rewriteSeq (s.take i) E.initialWord)).count v ≤ 1 ∨
        List.length (E.rewriteSeq (s.drop i) [.nonterminal v]) ≤ 1)
  (i : ℕ)
  (hi : i < s.length - 1) :
    ReplacementIsOkay E
      (grammar.state E w s s_derives_w is_lult i (Nat.lt_of_lt_pred hi))
      s[i + 1]
      (grammar.state E w s s_derives_w is_lult (i + 1) (Nat.add_lt_of_lt_sub hi)) where
  nonterminals_prop := by
    unfold State.toList
    conv => rhs ;  unfold grammar.state State.get state.unknownNonterminals
    simp only
    --
    change let t := _ ; _ = t
    intro t
    --
    have : t = List.filter (fun v ↦ state.guesses E s (i + 1) v == Guess.unknown)
        (filterNonterminals (E.rewriteSeq (List.take (i + 1 + 1) s) E.initialWord)) := by
      unfold t
      exact List.ofFn_get _
    rw [this]
    clear this t
    --
    have : s.take (i + 1 + 1) = s.take (i + 1) ++ [s[i + 1]] :=
      List.take_succ_eq_append_getElem _
    rw [this]
    clear this
    --
    rw [rewriteSeq_seq_append]
    unfold State.applyTable GuessList.rewriteWord GuessList.rewriteSymbol
    simp only [grammar.state_toList_eq, rewriteSeq_seq_single]
    unfold state.unknownNonterminals state.sentential
    --
    induction E.rewriteSeq (List.take (i + 1) s) E.initialWord with
    | nil =>
      rfl
    | cons x xs ih =>
      cases x with
      | terminal a =>
        simp [ih]
      | nonterminal v =>
        simp only [filterNonterminals_cons]
        rw [List.filter_cons]
        split
        · rename_i hh
          rw [List.flatMap_cons, List.flatMap_append, filterNonterminals_append, ih]
          simp only [rewriteWord_cons, rewriteSymbol_nonterminal, filterNonterminals_append,
            List.filter_append, List.append_cancel_right_eq]
          induction E.table s[i + 1] v with
          | nil =>
            rfl
          | cons y ys ih =>
            cases y with
            | terminal a =>
              simp [ih]
            | nonterminal n =>
              simp only [List.flatMap_cons, filterNonterminals_append, ih,
                filterNonterminals_cons]
              split
              · rename_i heq
                rw [List.filter_cons]
                rw [grammar.state_guesses_eq] at heq
                simp [heq]
              · rename_i heq
                rw [List.filter_cons]
                rw [grammar.state_guesses_eq] at heq
                simp [heq, GuessList.rewriteSymbol]
              · rename_i heq
                rw [List.filter_cons]
                rw [grammar.state_guesses_eq] at heq
                simp [heq]
        · rename_i hh
          simp only [ih, rewriteWord_cons, rewriteSymbol_nonterminal, filterNonterminals_append,
            List.filter_append, List.self_eq_append_left, List.filter_eq_nil_iff, beq_iff_eq,
            GuessList.rewriteSymbol_nonterminal_unknown]
          intro a ha contra
          simp only [GuessList.rewriteSymbol] at contra
          split at contra <;> simp at contra
          rename_i heq
          --
          simp only [filterNonterminals, getNonterminal?, List.mem_filterMap] at ha
          obtain ⟨x, ha, ha'⟩ := ha
          split at ha'
          · simp at ha'
          rename_i b
          simp only [Option.some.injEq] at ha'
          subst ha'
          --
          have heq' := grammar.state_guesses_prop E s i (Nat.add_lt_of_lt_sub hi) _ _ ha
            (by simp_all)
          exact heq' heq
  guesses_prop := by
    intro v h
    simp only [grammar.state_guesses_eq] at ⊢ h
    unfold Guess.toList
    --
    let rec go : (t : _) → (ht : E.rewriteSeq (List.drop (i + 1 + 1) s) t = []) →
          (state.guesses E s (i + 1)).rewriteWord t = []
      | [], _ => rfl
      | x::xs, h => by
        rw [rewriteSeq_cons] at h
        simp only [List.append_eq_nil_iff] at h
        have R := go xs h.right
        replace h := h.left
        simp only [GuessList.rewriteWord_cons, R, List.append_nil]
        --
        unfold state.guesses GuessList.rewriteSymbol
        split
        · simp at h
        · simp [h]
    --
    let rec go2 (a') : (t : _) → (ht : E.rewriteSeq (List.drop (i + 1 + 1) s) t = [.terminal a']) →
          (state.guesses E s (i + 1)).rewriteWord t = [.terminal a']
      | [], h => by simp at h
      | x::xs, h => by
        rw [rewriteSeq_cons] at h
        cases hh : E.rewriteSeq (List.drop (i + 1 + 1) s) [x] with
        | nil =>
          rw [hh] at h
          have R := go2 a' xs h
          simp only [GuessList.rewriteWord_cons, R, List.append_left_eq_self]
          --
          unfold state.guesses GuessList.rewriteSymbol
          split
          · simp at hh
          · simp [hh]
        | cons y ys =>
          if hhh : y = .terminal a' ∧ ys = [] then
            obtain ⟨rfl, rfl⟩ := hhh
            rw [hh] at h
            simp only [List.cons_append, List.nil_append, List.cons.injEq, true_and] at h
            --
            have R := go xs h
            --
            simp only [GuessList.rewriteWord_cons, R, List.append_nil]
            --
            unfold state.guesses GuessList.rewriteSymbol
            split
            · simp only [rewriteSeq_terminal, List.cons.injEq, Symbol.terminal.injEq,
                and_true] at hh ⊢
              trivial
            · simp [hh]
          else
            simp only [not_and_or] at hhh
            obtain hhh | hhh := hhh
            · have : y ∈ [.terminal a'] := by
                rw [← h, hh]
                simp
              simp only [List.mem_cons, List.not_mem_nil, or_false] at this
              trivial
            · have : List.length [(.terminal a' : Symbol α V)] > 1 := by
                rw [← h, hh]
                simp_all
              simp at this
    --
    split
    · split
    · rename_i heq1 heq2
      unfold state.guesses at heq1
      split at heq1
      · rename_i heq
        have : s.drop (i + 1) = s[i + 1]::s.drop (i + 1 + 1) := List.drop_eq_getElem_cons _
        rw [this, rewriteSeq_seq_cons] at heq
        clear this
        simp only [rewriteWord_cons, rewriteSymbol_nonterminal, rewriteWord_nil,
          List.append_nil] at heq
        clear * - heq
        --
        --
        exact go (E.table s[i + 1] v) heq
      · trivial
      · trivial
      · trivial
    · rename_i a' h' heq1 heq2
      unfold state.guesses at heq1
      split at heq1
      · exfalso
        trivial
      · rename_i a'' heq3
        simp only [Guess.single.injEq] at heq1
        subst a''
        simp only [List.map_cons, List.map_nil]
        --
        have : s.drop (i + 1) = s[i + 1]::s.drop (i + 1 + 1) := List.drop_eq_getElem_cons _
        rw [this, rewriteSeq_seq_cons] at heq3
        simp only [rewriteWord_cons, rewriteSymbol_nonterminal, rewriteWord_nil,
          List.append_nil] at heq3
        exact go2 a' (E.table s[i + 1] v) heq3
      · exfalso
        trivial
      · exfalso
        trivial

protected def grammar.seq {α V T} [Fintype V] [DecidableEq V] [DecidableEq α]
  (E : EDT0LGrammar α V T)
  (w : List α)
  (s : List T)
  (s_derives_w : E.rewriteSeq s E.initialWord = w.map .terminal)
  (is_lult :
    ∀ (v : V) (i : ℕ),
      i ≤ s.length →
        (filterNonterminals (E.rewriteSeq (s.take i) E.initialWord)).count v ≤ 1 ∨
        List.length (E.rewriteSeq (s.drop i) [.nonterminal v]) ≤ 1) :
      List (Table α V T) :=
  .init :: (List.map
    (fun i ↦ grammar.table E w s s_derives_w is_lult i.val i.prop)
    (List.finRange s.length)) ++ [ .finish ]

protected def grammar.initState {α V T} [Fintype V] [DecidableEq V] [DecidableEq α]
  (E : EDT0LGrammar α V T) :
    State α V where
  finLength := ⟨1, by
    simp only [Nat.lt_add_left_iff_pos]
    have := Nonempty.intro E.initial
    exact Fintype.card_pos_iff.mpr this ⟩
  get' := fun x ↦ E.initial
  inj' := by
    intro x y h
    simp_all only
    ext : 1
    simp_all only [Fin.val_eq_zero]
  guesses := fun x ↦ Guess.unknown
  guesses_prop' := by
    intro i
    rfl

protected lemma grammar.intialReplacement {α V T} [Fintype V] [DecidableEq V] [DecidableEq α]
  (E : EDT0LGrammar α V T)
  (w : List α)
  (s : List T)
  (s_derives_w : E.rewriteSeq s E.initialWord = w.map .terminal)
  (is_lult :
    ∀ (v : V) (i : ℕ),
      i ≤ s.length →
        (filterNonterminals (E.rewriteSeq (s.take i) E.initialWord)).count v ≤ 1 ∨
        List.length (E.rewriteSeq (s.drop i) [.nonterminal v]) ≤ 1)
  (h : s.length > 0) :
    ReplacementIsOkay E
      (grammar.initState E)
      s[0]
      (grammar.state E w s s_derives_w is_lult 0 h) where
  nonterminals_prop := by
    simp only [grammar.state_toList_eq]
    unfold grammar.initState State.applyTable
    unfold state.unknownNonterminals state.sentential State.toList State.get
    simp only [List.ofFn_const, zero_add]
    unfold State.length
    simp only [List.replicate_one, List.flatMap_cons, List.flatMap_nil, List.append_nil]
    have : s.take 1 = [s[0]] := by
      rw [List.take_one]
      unfold List.head?
      split
      · trivial
      · rfl
    rw [this]
    simp only [rewriteSeq_seq_single, grammar.state_guesses_eq]
    unfold GuessList.rewriteWord GuessList.rewriteSymbol EDT0LGrammar.initialWord
    simp only [rewriteWord_cons, rewriteSymbol_nonterminal, rewriteWord_nil, List.append_nil]
    induction E.table s[0] E.initial with
    | nil =>
      rfl
    | cons x xs ih =>
      cases x with
      | terminal a =>
        simp [ih]
      | nonterminal v =>
        simp only [List.flatMap_cons, filterNonterminals_append, ih, filterNonterminals_cons]
        rw [List.filter_cons]
        split
        · simp_all
        · simp_all
        · simp_all
  guesses_prop := by
    intro v h
    unfold grammar.initState at h
    simp at h

protected lemma grammar.seq_prop {α V T} [Fintype V] [DecidableEq V] [DecidableEq α]
  (E : EDT0LGrammar α V T)
  (w : List α)
  (s : List T)
  (s_derives_w : E.rewriteSeq s E.initialWord = w.map .terminal)
  (is_lult :
    ∀ (v : V) (i : ℕ),
      i ≤ s.length →
        (filterNonterminals (E.rewriteSeq (s.take i) E.initialWord)).count v ≤ 1 ∨
        List.length (E.rewriteSeq (s.drop i) [.nonterminal v]) ≤ 1)
  (i : ℕ)
  (h : s.length > 0)
  (hi : i ≤ s.length) :
    NormalForm.stepP E
      ((grammar E).rewriteSeq ((grammar.seq E w s s_derives_w is_lult).take (i + 1))
        (grammar E).initialWord)
      (if i = 0 then grammar.initState E
       else grammar.state E w s s_derives_w is_lult (i - 1) (by omega))
      (E.rewriteSeq (s.take i) E.initialWord) := by
  classical
  induction i with
  | zero =>
    unfold grammar.seq
    simp only [zero_add, List.cons_append, List.take_succ_cons, List.take_zero,
      rewriteSeq_seq_single, rewriteSeq_refl]
    have hh := NormalForm.initP_apply_table E (grammar E).initialWord .init rfl
    simp only [↓reduceIte] at hh
    simp_all [grammar.initState]
  | succ j ih =>
    replace ih := ih (Nat.le_of_succ_le hi)
    have : List.take (j + 1 + 1) (grammar.seq E w s s_derives_w is_lult) =
        List.take (j + 1) (grammar.seq E w s s_derives_w is_lult) ++
          [(grammar.seq E w s s_derives_w is_lult).get ⟨j + 1, by
            unfold grammar.seq
            simp only [List.cons_append, List.length_cons, List.length_append, List.length_map,
              List.length_finRange, List.length_nil, zero_add]
            omega⟩] := by
      simp
    rw [this]
    clear this
    --
    rw [rewriteSeq_seq_append, rewriteSeq_seq_single]
    have : j < s.length := Nat.lt_of_lt_of_eq hi rfl
    conv =>
      arg 2
      lhs
      unfold grammar.seq
      simp only [List.cons_append, List.length_cons, List.get_eq_getElem, List.getElem_cons_succ,
        List.length_map, List.length_finRange, this, List.getElem_append_left, List.getElem_map,
        List.getElem_finRange, Fin.cast_mk]
      unfold grammar.table
    simp only [Nat.add_eq_zero_iff, one_ne_zero, and_false, ↓reduceIte, Nat.add_one_sub_one]
    --
    cases hih : ih with
    | intro u h₀ h₁ h₂ hww h_u
    --
    cases j with
    | zero =>
      simp only [zero_add, ↓reduceIte, List.take_zero, rewriteSeq_refl] at ih
      have hh := NormalForm.stepP_apply_step E _ ih s[0]
        (grammar.state E w s s_derives_w is_lult 0 (Nat.lt_of_lt_of_eq this rfl))
        u h₀ h₁ h₂ hww h_u hih
      --
      have := grammar.intialReplacement E w s s_derives_w is_lult h
      simp only [this, ↓reduceIte] at hh
      have : s.take 1 = [s[0]] := by
        rw [List.take_one]
        simp only [Option.toList_eq_singleton_iff]
        unfold List.head?
        split
        · trivial
        · rfl
      rw [this]
      --
      simp only [zero_add, rewriteSeq_seq_single]
      exact hh
    | succ k =>
      have hh := NormalForm.stepP_apply_step E _ ih s[k + 1]
        (grammar.state E w s s_derives_w is_lult (k + 1) (Nat.lt_of_lt_of_eq hi rfl))
        u h₀ h₁ h₂ hww h_u hih
      simp only [Nat.add_eq_zero_iff, one_ne_zero, and_false, ↓reduceIte, Nat.add_one_sub_one] at hh
      --
      have := grammar.table_prop E w s s_derives_w is_lult k (Nat.lt_sub_of_add_lt hi)
      simp only [this, ↓reduceIte] at hh
      --
      have : List.take (k + 1 + 1) s = s.take (k+1) ++ [s[k+1]] :=
        List.take_succ_eq_append_getElem (by trivial)
      rw [this]
      clear this
      --
      rw [rewriteSeq_seq_append,rewriteSeq_seq_single]
      exact hh

lemma grammar_language_imp' {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  (hE : E.IsLULT)
  (w : List α)
  (h : w ∈ E.language) :
    w ∈ (grammar E).language := by
  obtain ⟨s, hs, h⟩ := hE _ h
  --
  --
  have s_len : s.length > 0 := by
    by_contra contra
    simp only [gt_iff_lt, not_lt, Nat.le_zero_eq, List.length_eq_zero_iff] at contra
    subst contra
    simp only [rewriteSeq_refl] at hs
    have : (.nonterminal E.initial : Symbol α V) ∈ List.map .terminal w := by
      rw [← hs, EDT0LGrammar.initialWord]
      exact List.mem_singleton_self (Symbol.nonterminal E.initial)
    simp at this
  --
  have : (grammar E).rewriteSeq
      (grammar.seq E w s hs h)
      (grammar E).initialWord = w.map .terminal := by
    have : grammar.seq E w s hs h = (grammar.seq E w s hs h).take (s.length + 1) ++
        ((grammar.seq E w s hs h).drop (s.length + 1)) :=
      Eq.symm (List.take_append_drop _ (grammar.seq E w s hs h))
    rw [this, rewriteSeq_seq_append]
    conv =>
      lhs
      arg 2
      unfold grammar.seq
      simp only [List.cons_append, List.drop_succ_cons, List.length_map,
        List.length_finRange, List.drop_left']
    rw [rewriteSeq_seq_single]
    --
    have h'' := grammar.seq_prop E w s hs h s.length s_len (Nat.le_refl s.length)
    --
    simp only [List.length_eq_zero_iff, List.take_length] at h''
    split at h''
    · simp_all
    --
    have := grammar.state_final E w s hs h s_len
    rw [this] at h''
    clear this
    --
    simp only [hs] at h''
    --
    cases hp : h'' with
    | intro u h₀ h₁ h₂ hww h_u =>
    --
    have accept := NormalForm.stepP_apply_finish E _ h'' u h₀ h₁ h₂ hww h_u hp
    simp only [↓reduceIte] at accept
    --
    simp only [GuessList.empty_rewriteWord] at h_u
    --
    have : u = w.map .terminal := by
      clear * - h_u h₀
      induction u generalizing w with
      | nil =>
        simp only [unlabelSententialWord_nil, List.nil_eq, List.map_eq_nil_iff] at h_u
        subst w
        rfl
      | cons x xs ih =>
        cases x with
        | terminal a =>
          simp only [unlabelSententialWord_cons_terminal] at h_u
          replace ih := ih (w.drop 1) (fun x ↦ by simp_all)
            (by
              have u' := id h_u
              rw [← List.take_append_drop 1 w, List.map_append] at h_u
              simp only [List.map_take] at h_u
              rw [List.take_one] at h_u
              unfold List.head? at h_u
              split at h_u
              · rename_i heq
                rw [heq] at u'
                simp at u'
              --
              rename_i a' as ha
              simp only [Option.toList_some, List.cons_append, List.nil_append,
                List.cons.injEq] at h_u
              exact h_u.right)
          rw [ih]
          --
          replace h_u := congrArg (List.take 1) h_u
          simp only [List.take_succ_cons, List.take_zero, ← List.map_take, List.take_one] at h_u
          --
          unfold List.head? at h_u
          split at h_u
          · simp at h_u
          --
          simp only [Option.toList_some, List.map_cons, List.map_nil, List.cons.injEq,
            Symbol.terminal.injEq, and_true] at h_u
          subst h_u
          --
          simp
        | nonterminal v =>
          replace h₀ := h₀ v List.mem_cons_self
          split at h₀
          · exfalso
            rename_i n q k
            subst h₀
            have : (State.empty (α := α) (V := V)).length = 0 := rfl
            rw [this] at k
            exact Fin.isEmpty'.elim k
          · trivial
    rw [this] at accept
    have ⟨h, h'⟩ := accept
    rw [h]
    clear * -
    simp
  unfold EDT0LGrammar.language
  change EDT0LGrammar.Generates _ _
  unfold EDT0LGrammar.Generates
  rw [derives_iff_rewriteSeq]
  exact ⟨grammar.seq E w s hs h, this⟩

@[simp]
lemma grammar_language_eq {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T)
  (hE : E.IsLULT) :
    (grammar E).language = E.language := by
  ext1 x
  constructor
  · exact grammar_language_imp E x
  · exact grammar_language_imp' E hE x

lemma grammar_isFiniteIndex {α V T}
  [Fintype V] [DecidableEq α] [DecidableEq V]
  (E : EDT0LGrammar α V T) :
    (grammar E).IsIndex (Fintype.card V + 1) := by
  intro w h
  have normal : NormalForm E w := NormalForm.generated E w h
  cases normal with
  | dead prop =>
    obtain ⟨x, rfl⟩ := prop
    simp
  | init prop =>
    obtain ⟨rfl⟩ := prop
    simp
  | accepted u prop =>
    obtain ⟨rfl,_⟩ := prop
    simp
  | step q ww prop =>
    obtain ⟨a,b,rfl,hh,d,e⟩ := prop
    simp only [filterNonterminals_cons, List.length_cons, Nat.add_le_add_iff_right, ge_iff_le]
    -- simp only [SymbolIsNonterminal_nonterminal, List.countP_cons_of_pos, add_le_add_iff_right,
    --   ge_iff_le]
    clear * - hh b
    replace hh := congrArg List.length hh
    --
    unfold State.toList at hh
    simp only [List.length_ofFn] at hh
    unfold State.length at hh
    replace hh: (filterNonterminals (unlabelSententialWord a)).length < Fintype.card V + 1 := by
      rw [← hh]
      exact q.finLength.isLt
    --
    have go
      (a : List (Symbol α (Nonterminal α V)))
      (b : ∀ (x : Nonterminal α V),
          Symbol.nonterminal x ∈ a →
            match x with
            | Nonterminal.regular q_1 i => q = q_1
            | x => False) :
        (filterNonterminals (unlabelSententialWord a)).length =
          (filterNonterminals a).length := by
      induction a with
      | nil =>
        simp
      | cons a as ih =>
        replace ih := ih (by
          intro x hx
          replace h := b x (List.mem_cons_of_mem a hx)
          split <;> simp_all)
        cases a with
        | terminal x =>
          simp only [unlabelSententialWord_cons_terminal, filterNonterminals_cons]
          exact ih
        | nonterminal x =>
          replace b := b x List.mem_cons_self
          split at b
          · subst b
            simp only [unlabelSententialWord_cons_nonterminal, filterNonterminals_cons,
              List.length_cons, Nat.add_right_cancel_iff]
            exact ih
          · trivial
    --
    rw [go a b] at hh
    exact Nat.le_of_succ_le_succ hh

end LULT2EDT0L
end EDT0LGrammar

private lemma Language.isLULT_imp_isFiniteIndexEDT0L_fin {α} [Finite α] (L : Language α)
  (h : L.IsLULT) :
    L.IsFiniteIndexEDT0L := by
  classical
  obtain ⟨n,m,E,is_lult,rfl⟩ := h
  rw [← EDT0LGrammar.LULT2EDT0L.grammar_language_eq E is_lult]
  use n + 1
  have := Fintype.ofFinite α
  refine EDT0LGrammar.isIndex_imp_language_isEDT0LOfIndex
    (EDT0LGrammar.LULT2EDT0L.grammar E) (n + 1) ?_
  have : (EDT0LGrammar.LULT2EDT0L.grammar E).IsIndex (Fintype.card _ + 1) :=
    EDT0LGrammar.LULT2EDT0L.grammar_isFiniteIndex E
  simpa

lemma Language.isLULT_imp_isFiniteIndexEDT0L {α} (L : Language α) (h : L.IsLULT) :
    L.IsFiniteIndexEDT0L := by
  classical
  obtain ⟨n,m,E,is_lult,rfl⟩ := h
  rw [← EDT0LGrammar.attach_isLULT_iff] at is_lult
  have is_fi_edt0l := Language.isLULT_imp_isFiniteIndexEDT0L_fin E.attach.language
      ⟨_,_,_,is_lult,rfl⟩
  obtain ⟨k,⟨n',m',E',h',h''⟩⟩ := is_fi_edt0l
  have H := congrArg (Language.map Subtype.val) h''
  simp only [EDT0LGrammar.language_eq_attach_language_map_val] at H
  rw [← H]
  apply Language.map_isFiniteIndexEDT0L
  exact ⟨k,_,_,E',h',rfl⟩

